### ISSUE TITLE
Pagination of lists error - do not display if no more to show

### ISSUE THREAD

**Issue by BionicClick** [madoublet/respond#185]
Hello,

i have noticed that in all instances where there is the ability to add a list of pages or posts or events to a page, and you get the option to paginate... that the pagination shows no matter what.... and if there are NO more links to show in the list.. it simply disappears.

this is causing some pretty severe confusion among site visitors,and im getting a few emails about it already.

is there any way to stop the display of the "next" link for pagination if there is nothing to paginate?

for example... if you have two events, and you choose to paginate by 10... the pagination link shows below the two events, but it should never show unless there are additional events or lists to show.  when you click that link and there is nothing to show, the entire block of content disappears, no message no nothing.

**Comment by cgaisberger** [comment]
While it seems that the "next" button is now hidden when there are no more pages to to browse, the numbered page buttons still are. See the screenshot I have taken from respondcms.com's blog.

![Uploading 2015-03-13 08_26_45-Respond - Blog.jpg . . .]()
