### ISSUE TITLE
Suggestion: Tour introduction popup screen needs to be more visible

### ISSUE THREAD

**Issue by joebordes** [madoublet/respond#232]
I just logged in for the first time in a new site and I had to look twice to see the tour/introduction popup. See attached image. I think maybe just a border would make it stand out a little more

![tourpopupneedsmorerelieve](https://cloud.githubusercontent.com/assets/1237191/5695968/2d78d5da-99bb-11e4-88c5-b4d69c676714.png)

![captura de pantalla de 2015-01-11 17 55 20](https://cloud.githubusercontent.com/assets/1237191/5695971/333885e2-99bb-11e4-8054-0169bdbe6d9e.png)

**Comment by joebordes** [comment]
The last tour popup isn't translated and is another example of the need to stand out a little more:

![lasttourscreennottranslatedandnotvisible](https://cloud.githubusercontent.com/assets/1237191/5695983/9a2c2bd2-99bb-11e4-97c6-e8c9d0cdacf4.png)

**Comment by joebordes** [comment]
BTW: this is really nice feature and I like the way it moves around to call your attention. :+1:

**Comment by madoublet** [comment]
Thanks!  I added a border so it should be more visible.  There is suppose to be a drop shadow as well.  But, that might not show due to browser issues.

**Comment by madoublet** [comment]
I also added a translation for that last step.
