### ISSUE TITLE
Firefox can't access SKU download picklist

### ISSUE THREAD

**Issue by joebordes** [madoublet/respond#234]
![firefoxsku](https://cloud.githubusercontent.com/assets/1237191/5696108/9dc8f418-99c1-11e4-9288-ac7e90af009e.png)

This works correctly in Chrome:

![chromesku](https://cloud.githubusercontent.com/assets/1237191/5696109/aeeaac78-99c1-11e4-9491-79e453768f57.png)

**Comment by madoublet** [comment]
Interesting.  I will have to test this on my Windows machine later today.  This is not a problem on the Mac.  But, I suspect it is related to the text boxes being below the label.  On my machine, they are to the right of the label.  I wonder if how the scrollbar is displayed causes an issue.

**Comment by joebordes** [comment]
I am working on Linux, just FYI.

This change seems to fix the issue, or at least it permits me to access the information. Not quite sure if that is the correct solution though

```
diff --git a/css/content.css b/css/content.css
index e62e0c6..ab97f5e 100644
--- a/css/content.css
+++ b/css/content.css
@@ -525,6 +525,7 @@ body.content{}
 	background-color: #f8f8f8;
 	overflow: scroll;
 	padding-bottom: 100px;
+	z-index: 110;
 }
 
 	.configure .context-menu{
```
