### ISSUE TITLE
AngularJS Error On HTML Block Open/Close

### ISSUE THREAD

**Issue by joebordes** [madoublet/respond#235]
Click on the down arrow to open HTML editor and get error. It all seems to work correctly despite the error.

![angularjserroronhtmlblockopen](https://cloud.githubusercontent.com/assets/1237191/5696180/adc0f192-99c4-11e4-9766-791d2857cdc9.png)

**Comment by joebordes** [comment]
This is happening also on Video down/up arrow

**Comment by madoublet** [comment]
Yeah, that is some odd Angular thing.  I was able to fix it.
