### ISSUE TITLE
Button for single-column layout actually creates a two-column layout

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#237]
Bug is present in both "master" and "respond4" branches.  

Steps to reproduce:

1.  Open a page and add a one-column layout block.  You'll get a two-column layout block.

It doesn't seem to generate any new errors on the Javascript console.

Proof:  http://screencast.com/t/XO5FIa8Nx

**Comment by madoublet** [comment]
Thanks!  This should be fixed now.
