### ISSUE TITLE
Dropzone becomes invisible after uploading an image

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#239]
### Version
Respond 4 (master branch, current as of 2015-01-19)

### Description
After you upload an image by clicking on the dropzone in the file modal, the dropzone icon becomes invisible.  It's still there and still clickable, but not visible.

### Steps to reproduce

1) Add an image to a page
2) In the modal file dialog, upload an image file.
3) Add another image.  You'll see that the icon labeled "Drag file here or click to upload files" is no longer visible.

### Video
http://screencast.com/t/1eCRF9Vyeoqj

**Comment by madoublet** [comment]
Yeah, that behavior is a bit odd.  I will see if there is a fix for that.

**Comment by madoublet** [comment]
That is actually the default behavior of the plugin.  It looks like he just received a new version, so I am going to look into upgrading it in a later release.  I am going to close this for now.
