### ISSUE TITLE
Uploading a Zip breaks "Files"

### ISSUE THREAD

**Issue by danielecb** [madoublet/respond#240]
Hi,
when uploading a Zip in the "Files" page, the file gets uploaded correctly, but the page won't load anymore afterwards. Removing the file manually from the server fixes it.

Uploading it into "Digital Downloads" has the same effect.

Dan

**Comment by madoublet** [comment]
Thanks. I will take a look.

**Comment by axis80** [comment]
I just tried uploading a Zip to the "Files" page and it worked fine.  Yesterday I fixed a bug in the dev branch that was preventing non-image files from being uploaded to the Digital Downloads folder.  See e62e8e5c4d4ab54ed5bfcd359b82182d1fb17178 .  But, that didn't have any bearing on the main Files folder.

@danielecb can you please confirm whether this is still an issue for you?  Please use a small ZIP file with a simple filename (e.g. test.zip) so we can rule out filesize and special characters.  Also make sure you have the correct permissions on the /files/ folder.  Let us know what browser you're using, and also open open your browser's Javascript console and see if there are any errors there.  (Ctrl Shift J usually opens it)

I will close this issue after March 1 if no further feedback is given.

**Comment by danielecb** [comment]
Hi axis80, I opened this bug around a year ago and AFAIR we were on Respond 4.5 back then (maybe an even older version!).

We're now on 5.2, which I've just tested again with a zip and it just works fine (used Safari).

So I guess this can be closed. Thanks for looking into it!

Dan
