### ISSUE TITLE
Menu builder having issues

### ISSUE THREAD

**Issue by MikeKTT** [madoublet/respond#241]
In the menu builder I am often finding issues with the ordering functionality, specifically when working with sub-menu items.

Sometimes the layout of the menu items within the CMS is completely different to the presentation on the website itself. 

Is this a known issue? Is there a "trick" to working with this?

**Comment by madoublet** [comment]
I will take a look at it.  I tend to build simple menus, so I probably
don't run into this bug a whole lot.

**Comment by MikeKTT** [comment]
Okay. Just for instance in this case I have a menu with around 26 items on it. It seems that when moving things around and publishing, the correct order is saved as HTML, but within the CMS it has issues presenting the correct structure.

After some more playing this morning i've found it's not strictly happening on the sub menu level, and also applies to top level items also.

Happy to provide you a login to my installation if you need it. Currently running the latest respond4 branch.

**Comment by madoublet** [comment]
Could you email me a login?  I did some testing and did not see an issue.

**Comment by madoublet** [comment]
This should be fixed now in "respond4".  Pull it and give it a shot.  I think it was just some bad code in the ng-repeat.

**Comment by markvgo** [comment]
I have got the latest changes and am also having this problem

I have modified the 'primary' menu but when redisplay in the designer the 'about' and 'contact' keep showing in the middle even when I have moved to bottom. And other items are out of priority order.

The actual menu seems to render it the right order. That is the saved priority order.

**Comment by madoublet** [comment]
You will need to switch to the respond4 branch to get the latest.  I will publish it out to the main branch later this week.  You will need to update your setup b/c there were a lot of changes to that in the latest.
