### ISSUE TITLE
Adding links to images needs some attention

### ISSUE THREAD

**Issue by MichaelScottCode** [madoublet/respond#242]
As per your lastest commit, the new popout for links is much better I think. However it doesn't carry the functionality across for image based links. Specifically the dropdowns for files/internal links do not fit within the sidebar.

Attached screenshot to show the issue.

![screen shot 2015-01-24 at 18 48 32](https://cloud.githubusercontent.com/assets/2870589/5888524/15b2ad56-a3fa-11e4-988f-a6a85b190a41.png)

**Comment by madoublet** [comment]
This looks like it needs some work.  I will take a look.
