### ISSUE TITLE
Link dialog bug

### ISSUE THREAD

**Issue by Lorenzbi** [madoublet/respond#243]
Link dialog doesn't work when the selection is before the link. To reproduce click on the left part of the first letter in the link.

**Comment by madoublet** [comment]
This should be fixed in the dev (respond4) branch.  I have updated it so that when you click on a link in the editor, it automatically brings up the link dialog.  Try this and let me know if it fixes your problem.

**Comment by Lorenzbi** [comment]
It's really minor but if you click the left part of the first letter then the dialog is empty.

**Comment by madoublet** [comment]
I will see if I can fix that.  I am going to close this b/c this seems like a minor issue.
