### ISSUE TITLE
RTL Defaulting on mobile

### ISSUE THREAD

**Issue by MichaelScottCode** [madoublet/respond#244]
Spotted this is on Android's Chrome browser... Text and form inputs are displaying aligned right rather than left. It doesn't happen when loading in a desktop browser and resizing down, just when using Android's Chrome. I can't speak for Safari on iOS or any other mobile browser.

**Comment by madoublet** [comment]
Is this on the app or the sites themselves?

**Comment by MikeKTT** [comment]
The app itself. Sites seem fine.
