### ISSUE TITLE
site trying to load translation locale for es

### ISSUE THREAD

**Issue by joebordes** [madoublet/respond#247]
The website is looking for es translation file although it has already correctly loaded es-ES which is in the code. I think it shouldn't be trying to load es because es-ES is there and working correctly

![site_local_error](https://cloud.githubusercontent.com/assets/1237191/6092111/67c26ac6-aece-11e4-8b98-1fe59d54d527.png)

**Comment by madoublet** [comment]
I don't see anyway to correct this.  It appears the i18next library tries to load es and then if that fails tries es-es.  

http://i18next.com/pages/doc_init.html

**Comment by joebordes** [comment]
I see. It seems more an issue of i18next because it does load the es-ES correctly but it keeps on loading the es even though the es-ES worked.

Do you think it is worth informing on that project?

**Comment by madoublet** [comment]
I am going to close this for now.
