### ISSUE TITLE
Social button URLs cannot be set from theme settings screen

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#259]
Social buttons exist in the footer of all themes, but are not configurable via the theme settings page.  The only way to change them is to edit the theme, which means that multiple sites can't run on the same theme.  I assume this is something you simply haven't had time to get to.

I can implement this, but before I start editing files I want to make sure of how you want it to work.  I was thinking I would add a "social buttons" section to each themes configure.json file, with url (or text) inputs for each social network (and also email).  If a URL was pasted into a field, its respective button would appear on the site.  If it was blank, that button would simply not be shown.

Let me know if that implementation is OK, or if you would prefer a different approach.

**Comment by madoublet** [comment]
Hold on this for now.  I plan to make the footer editable as part of Respond 4.5.  It will be included in themes with the respond-content component.  I am going to make it an option to have this run at publish time for theme layouts as well. 

So, we might want to develop this as a plugin instead.

**Comment by madoublet** [comment]
You can now edit the footer as part of the 4.5 branch.  I still think a "social" plugin makes sense.  But, I am closing this for now.

**Comment by axis80** [comment]
I am running up against this issue again.  The editable footer is a good solution for many cases, but it still doesn't really help with the social buttons.  My users are not that sophisticated.  if I give them an included "footer social buttons" page to edit, they're going to mangle it.

I really would like to make the social buttons configurable from the theme settings panel so I can lock down the styling and markup, and make them easier for the end user to edit.  Exactly how Shopify does it:

![image](https://cloud.githubusercontent.com/assets/6088477/6991410/268dd82a-da60-11e4-802b-ce962d2c87c2.png)

I'm thinking the best way to accomplish this is to create a <respond-social> component.  It doesn't necessarily have to be used by all themes, but it will be there for people who want to use it in theme development.

Questions:

1. Are you OK with this?  I don't want to put in the work unless it stands a chance of being merged.

2. How do I access a theme setting from a Polymer element?  I see a reference to respond.site.settings.Language in the <respond-languages> component so I figure the syntax must be something like that.

I can figure out everything else on my own by analyzing the existing components.  I just need a pointer in the right direction...

Thanks!

**Comment by madoublet** [comment]
I think this is a cool idea and would definitely accept the pull request.  Right now, I am working on converting the existing components to Polymer 0.8 (as it was just released on Friday).  This is a pretty big change for the platform.  So, most of the components will have to be re-written to work with the update.  So, I would recommend holding off until you see the 0.8 stuff getting checked into development.

**Comment by madoublet** [comment]
You can read a little about 0.8 here: https://www.polymer-project.org/0.8/
