### ISSUE TITLE
Google Cloud Storage

### ISSUE THREAD

**Issue by zumbrunnen** [madoublet/respond#262]
Hi!

I've recently discovered this CMS... And it's great! Thank you!

I host my apps and stuff on Google Cloud (Google Compute Engine), thus it would be great to have a Google Cloud Storage adapter.

Are there any plans to implement this? I've already looked up the code and it would be pretty straight-forward:

* Install and use [Google's API client for PHP](https://cloud.google.com/compute/docs/api/libraries) (installation via Composer is possible).
* Add `api/libs/GCS.php` with the same functions like the S3 lib.
* Replace `FILES_ON_S3` (boolean) with a more generic `FILES_ON` (String, with the possible values: "local", "S3" or "GCE").
* Adjust `setup.php` and the help texts and back-end HTML accordingly. 

I'm a PHP n00b - but I could give this I try, if 

1. you think this is a good idea,
2. there's a need for GCS and
3. some PHP guru and/or RespondCMS expert could help me in case I have some questions.

Dave

**Comment by madoublet** [comment]
Yes, I think this would be cool.  Give it a shot and email me if you run into any issues (matt@matthewsmith.com).

**Comment by pablotreo** [comment]
Hello zumbrunnen how was the installation ?

**Comment by zumbrunnen** [comment]
Hi @pablotreo 
The installation was no problem. Anyway, I've found out, that replacing the Bootstrap framework by anything other is rather painful. Bootstrap seems to be used pretty deep in the system. Although I'm a long-term Bootstrap user, I want to use something different. So I'm thinking about changing CMS :confounded: 

That's the reason why I have not begun with implementing a GCS adapter. I'm sorry for the bad news...

**Comment by madoublet** [comment]
No worries.
