### ISSUE TITLE
content widget - on load - missing slash after {{site.ImagesUrl}}

### ISSUE THREAD

**Issue by lefke** [madoublet/respond#263]
Missing slash between {{site.ImagesUrl}} and files, fine when viewing page directly, but when content is loaded into page using the 'content' widget, image urls break.

eg.
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (app_tablet_plane.jpg, line 0)
...co.uk/{{site.ImagesUrl}}files/app_tablet_plane.jpg

**Comment by madoublet** [comment]
Is this breaking for you when you set render=publish in like a layout?  Or are you including it in a page using a widget?  I fixed the render=publish issue, but can't reproduce if I include it in a page.

**Comment by lefke** [comment]
I've confused things I think, maybe there is a better way to do the hack
that I'm doing.

If I embed the following with the code widget

<div class="home-gallery right-layout">
  <div class="gallery-cell">
     <respond-content url="slideshow/what-are-the-benefits"
render="publish"></respond-content>
  </div>
  <div class="gallery-cell">
     <respond-content url="slideshow/our-impact"
render="publish"></respond-content>
  </div>
  <div class="gallery-cell">
     <respond-content url="slideshow/how-does-it-work"
render="publish"></respond-content>
  </div>
</div>


the image urls break, so on those original pages I copy the image code and
insert the images with another html embed widget.
e.g. what-are-the-benefits:

<div id="image-1" class="respond-image" data-display="standalone"
data-i18n="54fcaee12366d.image-1">
    <img src="files/pilot-web.jpg" data-location="local">
</div>



----------------------------
Lefke Kerr
+447912440128
lefke.net
<http://lefke.net>
