### ISSUE TITLE
Form not publishing the id and name attributes for inputs

### ISSUE THREAD

**Issue by Burden50** [madoublet/respond#264]
When you create a form and give the fields names the id does not get published to the page only blank attributes get added.

This is a text area generated in the published page note that the id="" and the name=""
```
<textarea id="" name="" class="form-control"></textarea>
```

**Comment by madoublet** [comment]
Are you on 4.5?  I am not seeing this issue at all.  I created two test forms and see the ids coming through.

http://dev.respondcms.com/sites/next/page/new-form
http://dev.respondcms.com/sites/next/page/contact

Can you provide steps to reproduce it?

**Comment by Burden50** [comment]
The issue I described occurs on the link you posted as well. I looked into it further it seems to only happen on Safari when I tried on Chrome it loaded correctly.

**Comment by madoublet** [comment]
Appears to have the same problem in Firefox as well.  So, that will be easier to debug.  I will take a look.

**Comment by madoublet** [comment]
I have a fix in there.  The problem is that Safari and Firefox do not handle the ID attribute for custom elements.  So, I will have to change these.  The fix changes the id to "formid" and "fieldid".  I will also need to update the default pages as well.

**Comment by madoublet** [comment]
I might make this more generic tomorrow.  So, I am not moving it out of dev yet.  I think something like "elementid" or "componentid" could be used across the board.

**Comment by Burden50** [comment]
Thanks for the quick fix matt! Yah making a generic case would be good I will leave this issue open you can close it whenever you code the generic case :D

**Comment by Burden50** [comment]
Now I am getting id="Undefined" & name="Undefined" I guess I will wait till its in the master branch.

**Comment by Burden50** [comment]
Fixed in latest build!
