### ISSUE TITLE
Broken author thumbnail photo on blog page (Respond 4.5)

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#272]
I do not have a photo assigned to my admin user account.  When I post a blog article, there is a broken image where my thumbnail photo should appear.  

The Chrome console reports that it's trying to load /files/thumbs/null as the image.  

I think the issue is in line 35 of sites/components/respond-meta.html:

`<template if="{{photo != ''}}">`

I think this line should be something like:

`<template if="{{photo}} != ''">`
or 
`<template if="{{photo}} != ''undefined">`

I don't see any changes when I alter that file, though.  It looks like it is a source file, which is compiled/minified into respond-build.html along with all the others, but I don't know how to regenerate that build file.  Are you using vulcanize?

**Comment by Burden50** [comment]
If you have vulcanize installed you can run the following command in the /INSTALL_DIR/app/site/components/ directory in order to rebuild the respond-build.html file with your changes.

```
vulcanize -o respond-build.html respond.html --inline --strip
```

**Comment by axis80** [comment]
Thanks Robert.  I will try that command and see if I can solve this issue the next chance I get.

**Comment by madoublet** [comment]
This is fixed in the latest build.
