### ISSUE TITLE
Menu components on pages in sub directories links to index (not /index)

### ISSUE THREAD

**Issue by Burden50** [madoublet/respond#274]
This is probably a major change and would take alot of revisions to solve but I thought it might be worth discussing.

In many places includes or file references are done without the leading slash making them relative to the working directory instead of the site root. This limits respond to only 2 levels of page depth root & a single type because if you try to go /type/type many files become unreferenced.

This also creates a bug with menu components on pages in sub directories because by default the menu links to index instead of /index

It would be nice for organization to have nested types.

**Comment by madoublet** [comment]
We'll use this issue to track the bug you talked about.  Long term, nested types probably makes sense, but I think there are better ways to use that time in the short term.

**Comment by Burden50** [comment]
Agreed there are lots of work arounds for this so no need to make a huge change but it should be kept in mind when writing new modules so that it can be a future solution :)
