### ISSUE TITLE
Search results include pages marked Include Only

### ISSUE THREAD

**Issue by Burden50** [madoublet/respond#275]
The search results include data that is marked include only. I did some investigation and it seems you are not writing these files to the site map as expected. My assumption was the search pulled from sitemap.xml for its data but it seems to be pulling from an api routing. 

~~Where does search get its data from @madoublet ?~~

Edit: So it looks like search pulls from the translations json file which includes all the pages I'm not quite sure how you would like to handle this so I will wait for guidance before implementing a solution.

**Comment by madoublet** [comment]
Yes, that is correct.  We will still need that translated, but it shouldn't show in search.  Tonight, I will add an IncludeOnly key, so that we can filter it from the results.  Something like this:

```javascript
    "54f087c80c604": {
		"pageId": "54f087c80c604",
		"name": "Footer",
		"url": "component/footer",
		"description": "This is the footer component used across pages.",
		"includeOnly": "1",
		"footer-h3-1": "Contact",
		"footer-p-1": "Give us a call at (123) 456-7890 or email us at&nbsp;<a href=\"mailto:sample@sample.com\">sample@sample.com</a>.",
		"footer-h3-2": "About",
		"footer-p-2": "This site is powered by <a href=\"http://respondcms.com\">Respond CMS</a>. Respond CMS is an open source content management system that you can use to build beautiful, responsive websites. The latest version features Bootstrap 3.0, robust themes, a complete REST API, and a beautiful UI."
	}
```

**Comment by Burden50** [comment]
Perfect!

**Comment by madoublet** [comment]
This should work now.
