### ISSUE TITLE
[Editor] Images do not take up proper block space

### ISSUE THREAD

**Issue by Burden50** [madoublet/respond#276]
When you page an image in the editor it does not properly expand the content box to the height of the image.

**Comment by madoublet** [comment]
That one would probably be tricky to implement in CSS.  It might just be easier to set it so that when you click on the column, the contentEditable div gets focus.

**Comment by Burden50** [comment]
Alternatively you could grab the image height on load using JS and adjust the content box

**Comment by Burden50** [comment]
This seems to be a fairly simple fix but I can't find the code the generates the content blocks.

The <img/> tag is getting generated outside of the editable content div. If you move it inside the div and remove this line of css 
```
width: calc(50% - 20px) !important;
```

**Comment by madoublet** [comment]
I cannot find a good solution for this.  It might be possible with flexbox or using JavaScript, but I am not sure it is worth the effort.  I am going to close this b/c it is not really a bug.
