### ISSUE TITLE
Changing logo from Branding screen results in fatal PHP error (4.5)

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#285]
Selecting or uploading a new logo from the Branding page results in this error:

PHP Fatal error:  Call to undefined method Publish::PublishSiteJSON() in /var/www/vhosts/www.example.com/respond/app/api/rest/site.php

Looking in api/libs/Publish.php, I see that there is indeed no PublishSiteJSON() method.  Maybe it is supposed to say PublishMenuJSON?

It doesn't look like this is fixed in 4.6, but I can't be sure because I'm still running 4.5.

**Comment by madoublet** [comment]
This should be fixed in the latest version (4.8).

**Comment by axis80** [comment]
I tested this in 4.8 and it does seem to be fixed.  Closing.
