### ISSUE TITLE
Files API broken with dev

### ISSUE THREAD

**Issue by Mike-Morris** [madoublet/respond#288]
Fatal error: Uncaught exception 'Tonic\NotFoundException' with message 'Resource matching URI "/files/list" not found' in /home/www/api/vendor/peej/tonic/src/Tonic/Application.php:199 Stack trace: #0 /home/www/api/dispatch.php(65): Tonic\Application->getResource(Object(Tonic\Request)) #1 {main} thrown in /home/www/api/vendor/peej/tonic/src/Tonic/Application.php on line 199

**Comment by madoublet** [comment]
Where are you seeing this error?

**Comment by Mike-Morris** [comment]
Ignore this, clearly I was drunk, this was from a GET request.
