### ISSUE TITLE
Textarea tags in HTML widget break the editor

### ISSUE THREAD

**Issue by romcart** [madoublet/respond#291]
To reproduce, add some HTML, including a textarea, to a page using the HTML widget in the editor. 

Simplified example:

```HTML
<div>
    Here is some HTML before the text area
</div>

<div>
    <textarea name="test"></textarea>
</div>

<div>
    Here is some HTML after the text area
</div>
```

After saving and publishing, if you load the page in the editor again, you will see this:

![Textarea problem](https://dl.dropboxusercontent.com/u/6516117/Respond/textarea_oops.png)

Notice the editor is broken, displaying any HTML after the textarea outside of the HTML widget.

**Comment by madoublet** [comment]
I just pushed a fix.  It fixed the problem in my testing.  But, let me know if it works for you.

**Comment by romcart** [comment]
Looks like that did the trick. Thanks!
