### ISSUE TITLE
Image slideshows / carousels not working in Firefox or IE (Respond 4.8)

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#292]
Open http://getaway.respond.website/index in Firefox 37.0.2 (Windows) or IE 11 (Windows).  The slideshow initially renders and then auto-advances to the end, but then it stops and the controls do not work.  It works fine in Chrome (Windows).

I tried cherry-picking commit 0c6bb570ab877bbd0e846cb61bcbf3c0f7f68dd2 since it seemed related, but that didn't help.

I'm going to post this to the Google Group as well, to see if anyone there knows how to use the Firefox debugger to figure out the cause.

**Comment by madoublet** [comment]
This seems to work for me in FF now.
