### ISSUE TITLE
HTML Widget won't expand in Chrome (Latest)

### ISSUE THREAD

**Issue by ChrisVitale** [madoublet/respond#294]
Looks like the HTML widget won't expand in Chrome. It expanded fine in IE and Firefox, but I'm completely unable to edit any text/code for the HTML widget as well as any widget that has a similar dropdown (Pre-formatted text, etc).

**Comment by madoublet** [comment]
Thanks.  I have experienced this before.  It appears to work if you close the tab on re-open Respond.  I will see if I can resolve the issue.

**Comment by ChrisVitale** [comment]
Yeah, seems to be intermittent. Half an hour later it decided to work properly.

**Comment by madoublet** [comment]
I wonder if it has to do with some odd JS caching.  I will see if I can replicate it.

**Comment by madoublet** [comment]
So
