### ISSUE TITLE
Alternative "backend stack" for Respond CMS ? If not, reusability of front end code ?

### ISSUE THREAD

**Issue by fabm22** [madoublet/respond#299]
Hi, 
Respond CMS looks amazing, good job. Nonetheless, I was wondering if there was any alternative implementation other than with PHP in particular ??

And if not, how hard would it be to use "only" the frontend AngularJS code and map all the REST apis calls to some other technology ?? 
Is there a best way to do that ? Has anybody tried this before ? 

Thansk a lot for your help!

**Comment by madoublet** [comment]
I am sure it is possible.  But, I have not seen an alternate implementation.

**Comment by fabm22** [comment]
Thanks for your answer. And you wouldn't have any particular advice on it? 
Is the API in some particular way tied to the backend technology (PHP), would you say?

Thanks a lot for advice.
