### ISSUE TITLE
Suggestion:  Images should have "standalone" alignment by default

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#300]
While training my clients on how to use the editor, I've noticed that they all have run into challenges when placing images for the first time.  Their confusion stems from the fact that, by default, the image appears on the page with a caption field to the right side of it.  To the first time user, it's apparently not very obvious that it's a caption field.

I suggest that new images should have "standalone" alignment by default.  This would slightly ease the learning curve of the editor.  It would also save me some mouse clicks.  95% of the time that I place an image onto a page, I don't want a caption next to it.

**Comment by madoublet** [comment]
I think this is a good suggestion.

**Comment by fizzl** [comment]
seconded :)

**Comment by axis80** [comment]
This change has been made in the dev branch.  New images are now set to standalone alignment by default.
