### ISSUE TITLE
Suggestion: Layouts should be wrapped in container by default

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#301]
In general, pages look better when layouts are wrapped in a container.  
I suggest that this should be the default when adding a new layout to a page.  This will give beginning users better results off the bat, thus easing the learning curve of the editor and making it more likely they'll stick with Respond.  Advanced users can set "Wrap in container = no" if they want that.

This will also save me some mouse clicks.  95% of the time that I create a new layout, I want it to be wrapped in a container.

**Comment by madoublet** [comment]
Interesting.  I will try this out.  I don't see much harm in doing this.
