### ISSUE TITLE
Can we add alt tags to images in the Image plugin?

### ISSUE THREAD

**Issue by modimanz** [madoublet/respond#302]
I got it working for me if you are interested:

	diff --git a/plugins/element/config/images.html b/plugins/element/config/images.html
	index baa76d0..5a82c37 100644
	--- a/plugins/element/config/images.html
	+++ b/plugins/element/config/images.html
	@@ -94,14 +94,20 @@
	 				
	 				
	 		</div>
	-		
	+	
	+		<div class="form-group">
	+			<label for="Alt">{{'Alt' | i18next}}</label>
	+			<input name="Alt" type="text" maxlength="128" class="form-control" 
	+				ng-model="node.alt">
	+		</div>
	+
	 		<div class="form-group pull-up">
	 			<label></label>
	 		    <input ng-model="node.lightbox" 
	 		    	ng-true-value="1" 
	 		    	ng-false-value="0" type="checkbox"> {{'Lightbox' | i18next}}
	 		</div>
	-		
	+
	 		<div class="form-group">
	 			<label for="link">{{'Title' | i18next}}</label>
	 			<input name="link" type="text" maxlength="128" class="form-control" 
	@@ -119,4 +125,4 @@
	 diff --git a/plugins/element/config/images.html b/plugins/element/config/images.html
	index baa76d0..5a82c37 100644
	--- a/plugins/element/config/images.html
	+++ b/plugins/element/config/images.html
	@@ -94,14 +94,20 @@
	 				
	 				
	 		</div>
	-		
	+	
	+		<div class="form-group">
	+			<label for="Alt">{{'Alt' | i18next}}</label>
	+			<input name="Alt" type="text" maxlength="128" class="form-control" 
	+				ng-model="node.alt">
	+		</div>
	+
	 		<div class="form-group pull-up">
	 			<label></label>
	 		    <input ng-model="node.lightbox" 
	 		    	ng-true-value="1" 
	 		    	ng-false-value="0" type="checkbox"> {{'Lightbox' | i18next}}
	 		</div>
	-		
	+
	 		<div class="form-group">
	 			<label for="link">{{'Title' | i18next}}</label>
	 			<input name="link" type="text" maxlength="128" class="form-control" 
	@@ -119,4 +125,4 @@
	 
	 </div>
	 
	-	
	\ No newline at end of file
	+	
	diff --git a/plugins/element/respond.element.js b/plugins/element/respond.element.js
	index 9510975..c720190 100644
	--- a/plugins/element/respond.element.js
	+++ b/plugins/element/respond.element.js
	@@ -1514,10 +1514,11 @@ respond.element.image = {
	 		
	 			var display = $(this).val();
	 			var src = $(node).find('img').attr('src');
	+      var alt = $(node).attr('data-alt');
	 			var html = $(node).find('[contentEditable=true]').html() || '';
	 			
	 			// update html
	-			$(node).html(respond.element.image.html(display, src, html));
	+			$(node).html(respond.element.image.html(display, src, html, alt));
	 			
	 		});
	 		
	@@ -1549,7 +1550,7 @@ respond.element.image = {
	 	},
	 	
	 	// helper method to get HTML for the image based on alignment
	-	html:function(display, src, html, isExternal){
	+	html:function(display, src, html, isExternal, alt){
	 		
	 		// set local vs external image
	 		var location = 'local';
	@@ -1558,19 +1559,20 @@ respond.element.image = {
	 			location = 'external';
	 		}
	 		
	+    alt_src = ' alt="' + alt + '"';
	 		var content = respond.editor.defaults.elementMenu +
	-					'<img src="' + src + '" data-location="' + location + '">' +
	+					'<img src="' + src + '" data-location="' + location + '" ' + alt_src + ' >' +
	 					'<div class="editable-content" contentEditable="true">' + html + '</div>';
	 		
	 		// build html
	 		if(display=='standalone'){
	 			content = respond.editor.defaults.elementMenu +
	-					'<img src="' + src + '" data-location="' + location + '">';
	+					'<img src="' + src + '" data-location="' + location + '" ' + alt_src + ' >';
	 		}
	 		else if(display=='right'){
	 			content = respond.editor.defaults.elementMenu +
	 					'<div class="editable-content" contentEditable="true">' + html + '</div>' +
	-					'<img src="' + src + '" data-location="' + location + '">';
	+					'<img src="' + src + '" data-location="' + location + '" ' + alt_src + ' >';
	 		}
	 		
	 		return content;
	@@ -1591,6 +1593,7 @@ respond.element.image = {
	 		
	 		$(node).find('img').attr('src', image.fullUrl);
	 		$(node).find('img').attr('data-location', location);
	+    $(node).find('img').attr('alt', '');
	 		
	 		// hide dialog
	 		$('#imagesDialog').modal('hide');
	@@ -1614,7 +1617,7 @@ respond.element.image = {
	 		
	 		// build html
	 		var html = respond.editor.defaults.elementMenu +
	-					'<img src="' + image.fullUrl + '" data-location="' + location +'">' +
	+					'<img src="' + image.fullUrl + '" data-location="' + location +'" alt="" >' +
	 					'<div class="editable-content" contentEditable="true"></div>';
	 					
	 		// tag attributes
	@@ -1623,6 +1626,7 @@ respond.element.image = {
	 		attrs['data-id'] = id;
	 		attrs['class'] = 'respond-image';
	 		attrs['data-cssclass'] = 'respond-image';
	+    attrs['data-alt'] = '';
	 		attrs['data-display'] = 'left';
	 		attrs['data-link'] = '';
	 		attrs['data-title'] = '';
	@@ -1695,6 +1699,7 @@ respond.element.image = {
	 		}
	 		
	 		var location = $(node).find('img').attr('data-location') || '';
	+    var alt = $(node).find('img').attr('alt') || '';
	 		var link = $(node).find('a').attr('href') || $(node).find('a').attr('ui-sref') || '';
	 		var title = $(node).find('a').attr('title') || '';
	 		var target = $(node).find('a').attr('target') || '';
	@@ -1725,7 +1730,7 @@ respond.element.image = {
	 		var display = $(node).attr('data-display') || 'left';
	 		
	 		// set html
	-		var html = respond.element.image.html(display, src, $(node).find('p').html(), isExternal);
	+		var html = respond.element.image.html(display, src, $(node).find('p').html(), isExternal, alt);
	 		
	 		// tag attributes
	 		var attrs = [];
	@@ -1738,6 +1743,7 @@ respond.element.image = {
	 		attrs['data-title'] = title;
	 		attrs['data-target'] = target;
	 		attrs['data-lightbox'] = lightbox;
	+    attrs['data-alt'] = alt;
	 		
	 		// return element
	 		return utilities.element('div', attrs, html);
	@@ -1756,6 +1762,7 @@ respond.element.image = {
	   		var target = $(node).attr('data-target') || '';
	   		var lightbox = $(node).attr('data-lightbox') || '';
	   		var isLightbox = false;
	+      var alt = $(node).attr('data-alt') || '';
	   		
	   		// set lightbox
	   		if(lightbox == '1'){
	@@ -1819,12 +1826,12 @@ respond.element.image = {
	 	  		}
	 	  		
	 	  		// set image tag
	-	  		img = '<img src="{{site.ImagesUrl}}' + src + '" data-location="local">';
	+	  		img = '<img src="{{site.ImagesUrl}}' + src + '" alt="' + alt + '" data-location="local">';
	 	  		
	 	  	}
	 	  	else{
	 		  	// set image tag
	-	  		img = '<img src="' + src + '" data-location="external">'; 	
	+	  		img = '<img src="' + src + '" alt="' + alt + '" data-location="external">'; 	
	 	  	}
	 </div>
	 
	-	
	\ No newline at end of file
	+	
	diff --git a/plugins/element/respond.element.js b/plugins/element/respond.element.js
	index 9510975..c720190 100644
	--- a/plugins/element/respond.element.js
	+++ b/plugins/element/respond.element.js
	@@ -1514,10 +1514,11 @@ respond.element.image = {
	 		
	 			var display = $(this).val();
	 			var src = $(node).find('img').attr('src');
	+      var alt = $(node).attr('data-alt');
	 			var html = $(node).find('[contentEditable=true]').html() || '';
	 			
	 			// update html
	-			$(node).html(respond.element.image.html(display, src, html));
	+			$(node).html(respond.element.image.html(display, src, html, alt));
	 			
	 		});
	 		
	@@ -1549,7 +1550,7 @@ respond.element.image = {
	 	},
	 	
	 	// helper method to get HTML for the image based on alignment
	-	html:function(display, src, html, isExternal){
	+	html:function(display, src, html, isExternal, alt){
	 		
	 		// set local vs external image
	 		var location = 'local';
	@@ -1558,19 +1559,20 @@ respond.element.image = {
	 			location = 'external';
	 		}
	 		
	+    alt_src = ' alt="' + alt + '"';
	 		var content = respond.editor.defaults.elementMenu +
	-					'<img src="' + src + '" data-location="' + location + '">' +
	+					'<img src="' + src + '" data-location="' + location + '" ' + alt_src + ' >' +
	 					'<div class="editable-content" contentEditable="true">' + html + '</div>';
	 		
	 		// build html
	 		if(display=='standalone'){
	 			content = respond.editor.defaults.elementMenu +
	-					'<img src="' + src + '" data-location="' + location + '">';
	+					'<img src="' + src + '" data-location="' + location + '" ' + alt_src + ' >';
	 		}
	 		else if(display=='right'){
	 			content = respond.editor.defaults.elementMenu +
	 					'<div class="editable-content" contentEditable="true">' + html + '</div>' +
	-					'<img src="' + src + '" data-location="' + location + '">';
	+					'<img src="' + src + '" data-location="' + location + '" ' + alt_src + ' >';
	 		}
	 		
	 		return content;
	@@ -1591,6 +1593,7 @@ respond.element.image = {
	 		
	 		$(node).find('img').attr('src', image.fullUrl);
	 		$(node).find('img').attr('data-location', location);
	+    $(node).find('img').attr('alt', '');
	 		
	 		// hide dialog
	 		$('#imagesDialog').modal('hide');
	@@ -1614,7 +1617,7 @@ respond.element.image = {
	 		
	 		// build html
	 		var html = respond.editor.defaults.elementMenu +
	-					'<img src="' + image.fullUrl + '" data-location="' + location +'">' +
	+					'<img src="' + image.fullUrl + '" data-location="' + location +'" alt="" >' +
	 					'<div class="editable-content" contentEditable="true"></div>';
	 					
	 		// tag attributes
	@@ -1623,6 +1626,7 @@ respond.element.image = {
	 		attrs['data-id'] = id;
	 		attrs['class'] = 'respond-image';
	 		attrs['data-cssclass'] = 'respond-image';
	+    attrs['data-alt'] = '';
	 		attrs['data-display'] = 'left';
	 		attrs['data-link'] = '';
	 		attrs['data-title'] = '';
	@@ -1695,6 +1699,7 @@ respond.element.image = {
	 		}
	 		
	 		var location = $(node).find('img').attr('data-location') || '';
	+    var alt = $(node).find('img').attr('alt') || '';
	 		var link = $(node).find('a').attr('href') || $(node).find('a').attr('ui-sref') || '';
	 		var title = $(node).find('a').attr('title') || '';
	 		var target = $(node).find('a').attr('target') || '';
	@@ -1725,7 +1730,7 @@ respond.element.image = {
	 		var display = $(node).attr('data-display') || 'left';
	 		
	 		// set html
	-		var html = respond.element.image.html(display, src, $(node).find('p').html(), isExternal);
	+		var html = respond.element.image.html(display, src, $(node).find('p').html(), isExternal, alt);
	 		
	 		// tag attributes
	 		var attrs = [];
	@@ -1738,6 +1743,7 @@ respond.element.image = {
	 		attrs['data-title'] = title;
	 		attrs['data-target'] = target;
	 		attrs['data-lightbox'] = lightbox;
	+    attrs['data-alt'] = alt;
	 		
	 		// return element
	 		return utilities.element('div', attrs, html);
	@@ -1756,6 +1762,7 @@ respond.element.image = {
	   		var target = $(node).attr('data-target') || '';
	   		var lightbox = $(node).attr('data-lightbox') || '';
	   		var isLightbox = false;
	+      var alt = $(node).attr('data-alt') || '';
	   		
	   		// set lightbox
	   		if(lightbox == '1'){
	@@ -1819,12 +1826,12 @@ respond.element.image = {
	 	  		}
	 	  		
	 	  		// set image tag
	-	  		img = '<img src="{{site.ImagesUrl}}' + src + '" data-location="local">';
	+	  		img = '<img src="{{site.ImagesUrl}}' + src + '" alt="' + alt + '" data-location="local">';
	 	  		
	 	  	}
	 	  	else{
	 		  	// set image tag
	-	  		img = '<img src="' + src + '" data-location="external">'; 	
	+	  		img = '<img src="' + src + '" alt="' + alt + '" data-location="external">'; 	
	 	  	}

**Comment by madoublet** [comment]
This looks good. Do you want to submit a pull request to the dev branch?

**Comment by modimanz** [comment]
Done https://github.com/madoublet/respond/pull/303 thanks
