### ISSUE TITLE
plugin.json is currently included in editor.json

### ISSUE THREAD

**Issue by stevejs** [madoublet/respond#308]
The Creating Plugins page (http://respondcms.com/documentation/creating-plugins) tells the learner to insert the json contained in plugin.json into editor.json, however such json already exists in editor.json lines 272-281.  Should this json be included in editor.json in the repo as is currently the case?  Or should it be removed? (Just seems like the state of the repo is out of sync with the website, no biggie)

**Comment by madoublet** [comment]
Yeah, I will remove that.  It must have slipped in during testing.  Thanks!
