### ISSUE TITLE
is it possible to do multi level articles ?

### ISSUE THREAD

**Issue by peterpisljar** [madoublet/respond#310]
title probably doesnt describe it well.... 

i would like to have structure like this:

/food   
/food/salads
/food/salads/greek
/food/salads/cesar
/food/soups
/food/soups/beef
/drinks
/drinks/alcohol

you get the idea ... each of the above would be an article (probably showing some kind of submenu to navigate subentries) 

i was able to make it work on my site by changing .htaccess a bit. then i was able to do what i wanted in two ways:

1) i created article food in type / ... then i created article food/salads  (in same type) etc ... it actually works. i needed to manually create directories in my site folder. but the files were placed there correctly. i also needed to modify index layout to point to url root for all inclusions (/css/ instead of css/)

2) i created article food in type / ... but then i created another type /food ... in this type i created articles salads and soups. then i created two more types ... /food/salads and /food/soups. in this types i added the articles greek, ceasar and beef.
it works just the same, but allows me to better organize my articles.

now my original question. is this already possible to do (and i complicated too much) ?
if not, is this something others would want ? the code for creating directories would need to be checked, index layouts would need to be updated to point to web root (/css/ instead of css/) and .htaccess needs to be updated (to overwrite /food to /food.html even if directory /food exists)

**Comment by peterpisljar** [comment]
i prepared a fix but have problems pushing the change:
5:46:31 PM Push failed: fatal: unable to access 'https://github.com/madoublet/respond.git/': The requested URL returned error: 403
any idea ?

**Comment by madoublet** [comment]
This is currently not possible in Respond by default.  But, I do have it on my radar as a future enhancement.

**Comment by peterpisljar** [comment]
could you add me to the list of contributors ? (thats probably the reason i cannot push)
