### ISSUE TITLE
Text color picker requires manaul copy paste color code

### ISSUE THREAD

**Issue by Maximumz** [madoublet/respond#312]
When adding for example <h1> then adding a color the color code will populate but if you need to add <p> & add the same color you need to open the color picker, copy the color code the paste into the feild for text color then publish or the changes will not take effect.

**Comment by Maximumz** [comment]
Sorry first issue raised, example is adding h1 & then adding paragraph

**Comment by axis80** [comment]
Which browser are you using?  The color picker works correctly for me in Chrome.

**Comment by Maximumz** [comment]
I was using Opera, I will test in other versions.

**Comment by Maximumz** [comment]
I have checked this in other browsers & it's the same. I may want h1 to be green the code will populate but if i also have a paragraph for example i want to be the same color the color picker when selecting the paragraph is already set to green & will not populate the code.  You need to open the color picker copy the code manually then paste it to populate the feild then save for it to take effect.
