### ISSUE TITLE
Image size control

### ISSUE THREAD

**Issue by Maximumz** [madoublet/respond#314]
When adding an image the default setting is text right of the image but when selecting standalone for the image, the image can blow out of proportion & fill the whole div. I am currently adding manual css styles to control the image sizes. Is there a more effective work around? Possibly an option to set sizes on the tool bar.

**Comment by axis80** [comment]
Currently the only solution (that I know of) is to scale the image smaller before uploading it.  It will still fill the div in the editor, but on the web site it will never display larger than actual size.

It would be nice if we could limit it to actual size in the editor as well, so it more accurately reflects the size it will appear on the site.  I think we'd just need to remove this line from editor.css:

width: calc(100% - 20px);

It would also be nice to set sizes on the toolbar, as you suggest.  Perhaps a slider that could set it to a percentage of the column width?  It seems like the type of thing that could cause additional layout issues.

**Comment by madoublet** [comment]
By default, Respond enables responsive images (e.g. max-width 100%).  I would just create a helper class like ".non-responsive" and override the max-width property.
