### ISSUE TITLE
Importing respond-cart.html causes vulcanize build process to fail

### ISSUE THREAD

**Issue by stevejs** [madoublet/respond#316]
The documentation for creating plugins (http://respondcms.com/documentation/creating-plugins) says to use the follow command to run the vulcanize build tool:

    vulcanize respond.html > respond-build.html --strip-comments --inline-css

Line 15 of site/components/respond.html 

    <link rel="import" href="respond-cart.html">

causes the vulcanize build process to fail.  I have not yet investigated why.  I commented out the line of code above and the vulcanize process (and my custom plugin) works fine.

**Comment by madoublet** [comment]
Interesting.  Any idea why this happens?  I can take a look, but I have not had this issue.

**Comment by stevejs** [comment]
I just tried debugging.  The only thing I noticed was that there wasn't a closing </tbody> tag in the table in the template.

**Comment by stevejs** [comment]
The immediate cause of failure is that the value returned from analyzer.js (vulcanize dependency) line 224

    importParse(htmlImport, href)

is null.  It's null because line 86 of import-parse.js 

    doc = dom5.parse(htmlString, {locationInfo: true});

throws an error:

    [TypeError: Cannot read property 'end' of undefined]

I tried tracing a little further, that's how I found out the tbody wasn't closed, but I kept getting the same error even after I closed it.

**Comment by stevejs** [comment]
Appears to be related to this issue which was just closed a week ago:

https://github.com/Polymer/vulcanize/issues/186

I don't think the changes made in the fix above have made it to the version on npm yet.

**Comment by stevejs** [comment]
No longer able to replicate this issue.  The issue appears to have been fixed by the vulcanize issue above (which has been fixed).  Closing this issue.
