### ISSUE TITLE
File uploads currently broken due multiple errors

### ISSUE THREAD

**Issue by fizzl** [madoublet/respond#319]
I upgraded to the latest dev branch. Most of the stuff seems to work fine.

When I tried to upload an image, I got a PHP Notice that HTTP_X_AUTH is not an index in Utilities.php. After some investigation, I figured that in some places there has been switch from Authorization header to X-Auth header. As a quick hack, I added check for both headers. I guess the consistency of the headers should be checked thoroughly.

After this, the image is seemingly uploaded, but it actually does not arrive in the files directory.

Sorry, I do not have time to debug any further now. Do you have any quick solution?

**Comment by fizzl** [comment]
You can find my hack on top of my forks dev branch. Probably not the ideal solution :)

**Comment by madoublet** [comment]
Sorry about that.  I just pushed a bug fix.  It should work now.

**Comment by madoublet** [comment]
This should be fixed now in dev.
