### ISSUE TITLE
use \Firebase\JWT\JWT; for latest development code of that project

### ISSUE THREAD

**Issue by joebordes** [madoublet/respond#325]
I just launched a "composer update". I received the latest version of firebase/JWT. I couldn't login to the application.

I had to add "use" in Utilities.php to get everything working again as per documentation in the JWT Readme. I attach the patch here in case it helps as I'm not sure that is the correct solution (or place to put the "use")

HTH

```
diff --git a/api/libs/Utilities.php b/api/libs/Utilities.php
index 5a970de..8fd9813 100644
--- a/api/libs/Utilities.php
+++ b/api/libs/Utilities.php
@@ -1,5 +1,5 @@
 <?php
-   
+use \Firebase\JWT\JWT;
 class Utilities
 {
        
```

**Comment by madoublet** [comment]
Thanks!  I think that makes sense.  I will do this before we release 5.1.

**Comment by joebordes** [comment]
I added this to the dev branch today
