### ISSUE TITLE
Having a bower.json listing all (js) dependencies in a cohesive way ?

### ISSUE THREAD

**Issue by fabm22** [madoublet/respond#327]
Would you be interested in having a bower.json with all dependencies currently used for the frontend code (angular, jquery-ui, etc etc.), potentially smoothing any futur upgrade of some of them ???

**Comment by madoublet** [comment]
Yes, that would be fantastic.  Especially, if they could be automatically minified and put into respond.libs.min.js.  I have been meaning to do that, but I have been working on some other stuff.

**Comment by madoublet** [comment]
If you decide to build it, please submit the PR to the dev branch. Thanks!
