### ISSUE TITLE
Question: How could I use just the editor?

### ISSUE THREAD

**Issue by menonsamir** [madoublet/respond#329]
Respond has an amazing layout editor for pages. Do you have any advice on how I'd go about 'splitting' that functionality out into a standalone Angular app?

I've noticed that most of the code related to the layout editor is in `/js/respond.editor.js`, `/templates/content.html`, and `/css/src/editor.css`. I've slowly begun to try to 'unwind' that editor code from the rest of it, but it's not terribly easy. The JS in particular has heavy coupling with the backend PHP server.

Any advice/tips/help you have on doing that would be greatly appreciated. You guys have done a great job on this!

**Comment by madoublet** [comment]
I am actually working on a project to do that.  No ETA yet.  But, I have made pretty good progress.

**Comment by menonsamir** [comment]
If you have the time/ability, I'd love to see what progress you've made (maybe put it on Github?). I think it could be an excellent project in its own right.

**Comment by madoublet** [comment]
Definitely, when I have it stable it will be available on Github.  Right now it is in a private repo.  It is still very much a work in progress.

**Comment by codegeek1001** [comment]
Hi Matt, would love this standalone editor app. Looking forward.
