### ISSUE TITLE
{{resources}} no longer works in template files

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#330]
The documentation mentions a {{resources}} mustache tag that can be used in template files as a quick reference pointing to the theme's resources folder, however this no longer appears to work and it doesn't seem to be implemented in /api/libs/Publish.php.  See http://www.respondcms.com/documentation/create-themes

We should either fix it so it works, or remove it from the documentation.  At the moment I am not sure which is best.  I am simply adding this issue to track it, and will look at it in more depth later.

**Comment by madoublet** [comment]
I removed this from the documentation.  I am not sure the value of this anymore, but we can certainly take a look at it.

FYI, I updated the mustache syntax documentation to be accurate.

http://respondcms.com/documentation/mustache
