### ISSUE TITLE
Run cms on port other than 80.

### ISSUE THREAD

**Issue by lazydino** [madoublet/respond#335]
How to run respond on different port than 80? I think I've done all the necessary work on changing ports.conf for Apache. Respond home page is rendered, but is complain not able to make api call due to CORS since I've switch the website port to 81.

I am running respond on Ubuntu 12.04 with apache2.

**Comment by madoublet** [comment]
You should be able to just adjust the APP_URL to make it work. 

define('APP_URL', 'http://app.myrespond.com:81');
