### ISSUE TITLE
Access-Control-Allow-Origin' Error

### ISSUE THREAD

**Issue by michaeltse** [madoublet/respond#337]
I am using DigitalOcean and followed the guide to setup already, 

Here is the link: http://icebreakwl.com/
But there is an error that stopping me from going further..

"XMLHttpRequest cannot load http://www.icebreakwl.com/api/site/validate/id. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://icebreakwl.com' is therefore not allowed access."

How to fix this please?

**Comment by madoublet** [comment]
The www does look like it works. 

http://www.icebreakwl.com/#/create

I typically recommend installing Respond on a subdomain.  But, you should be able to get the non-www working by putting it in the CORS list in setup.php.

define ('CORS', serialize (array (
	    'http://icebreakwl.com'
	    )));

**Comment by madoublet** [comment]
I am going to close this b/c it is not really a bug.

**Comment by michaeltse** [comment]
thank you @madoublet solved:)
