### ISSUE TITLE
CSS line-height error ??

### ISSUE THREAD

**Issue by joebordes** [madoublet/respond#338]
My IDE (Aptana) says that there is an error in one of the CSS files. I don't know if it is just a thing of my IDE or it is really an error. I also don't know what value I should put so I attach here a screen shot so you can act accordingly.
![respond_lineheightcss](https://cloud.githubusercontent.com/assets/1237191/9346924/ebf95de0-4622-11e5-984e-87a6de443a16.png)

**Comment by madoublet** [comment]
Yeah, it looks like the default is normal, not auto.

**Comment by joebordes** [comment]
done!
