### ISSUE TITLE
Cannot link to internal page anchors of pages loaded using lists

### ISSUE THREAD

**Issue by fizzl** [madoublet/respond#342]
I have a page

/pages/reallybigpage
that uses a list to load all of the content from another folder
/reallybigpagecontent/

The pages in /reallybigpagecontent/ have anchors like `<a name="#foo"></a> <a name="#bar"></a> ` and so on.

If I try to link to them from another page, using a link like /pages/reallybigpage#foo, it will open the /pages/reallybigpage and the anchor is actually in the url. However, the page does not jump to the correct place.

I tried using jquery to delay a function after page ready and then jumping to the correct place on the page. However, it seems that the anchor indicated in window.location.hash is not in the DOM content.

I don't seem to quite understand how the lists work.

**Comment by madoublet** [comment]
Respond uses <base> tags to make life a bit simpler on the CMS.  So, your internal anchors behave a little bit differently.  See this reference: http://webdesign.tutsplus.com/articles/quick-tip-set-relative-urls-with-the-base-tag--cms-21399

Let me know if that fixes your problem.

**Comment by fizzl** [comment]
Hello again!

My links now take me to the correct page, but they still do not take to the correct section of the page.

Internal links work within a page, but if I copy paste the url with the "#anchor"-url to another tab, it will not go to the correct place within the page.

**Comment by joebordes** [comment]
I just tried this on a site I am developing and it seems to work correctly. I recorded a video to try to help.

https://youtu.be/yLP714rCy8A

HTH

**Comment by axis80** [comment]
It sounds like this might be a race condition.  Your browser navigates to /pages/reallybigpage#foo but #foo doesn't yet exist in the DOM, so it fails to jump to that anchor.  Or, it may be that it works sometimes but doesn't work other times.

I have developed a few custom themes with custom jQuery, and have run into this problem all over the place.  I use setTimeout to wait for the DOM nodes to become available.  It really makes my jQuery code way more complicated than it needs to be, but it's the only way to deal with it reliably.  Here is some example code that waits for #navbar-right-content to appear:

$(window).load(function() {

  /* use setInterval to wait until right navbar content has been loaded
     into DOM, then vertically center the content */
  var checkNavbarRightContentExist = setInterval(function() {
    if ($('#navbar-right-content').length >= 1 ) {
      // OK, it exists now.
      clearInterval(checkNavbarRightContentExist);
      verticalCenterRightContent();
    }
  }, 300); // check every 300ms
});

I don't know how you would use setInterval to handle anchor jump links.  In any case - that's my take on the issue - that it sounds like a race condition.
