### ISSUE TITLE
Uncaught SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by glenskie16** [madoublet/respond#343]
For some reason i can not open up the cart. also nothing happens when i add an item to the cart either until i refresh the page.

This error is happening only on jbfirestick.pinecms.com

**Comment by madoublet** [comment]
I cannot reproduce this on my development or production versions, so there is not much I can do.  Perhaps try removing some scripts to isolate what script is causing the error.

**Comment by glenskie16** [comment]
This seemed to happen when i used the shipping calculation for 'by order ammount' and 'by order weight' then switching back to 'flat rate'.

**Comment by madoublet** [comment]
That did change anything for me.  I still can't reproduce this.
