### ISSUE TITLE
List as calendar not working for me in v5.2

### ISSUE THREAD

**Issue by Ekallatum** [madoublet/respond#344]
Hi, I try to use list with display as type 'calendar'. I already create pages with events parameters (start and end date ..) and i use them in my list.

When i try page llive, events are display in the calendar but i can't switch month, to see another event (older or after current month) . Is the good behavior? Perhaps forgot configuration ?

Thx.

Florent.

**Comment by madoublet** [comment]
Yeah, this was not implemented.  I have the code from a previous version, but it might take a few days to get it to work.

**Comment by trystant** [comment]
Hi, I am running into the same problem here. Was there any progress on this, or is there code or help that can make this a workable view? Thanks.
