### ISSUE TITLE
sub-menu URL not displayed

### ISSUE THREAD

**Issue by Maximumz** [madoublet/respond#345]
Hi, I am using Chromatic it works on the nav when it isn't collapsed but once the menu collapses for smaller devices, the sub-menu item is not displayed.

![pic](https://cloud.githubusercontent.com/assets/9372492/10709416/ea1f1e60-7a89-11e5-900e-30fd364bd31f.png)

**Comment by Maximumz** [comment]
Looking further, this is possibly something to do with jQuery or Javascript.

**Comment by madoublet** [comment]
Thanks!  I will test it out.
