### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by n3ssi3** [madoublet/respond#347]
Hey,

After having my first problems with the installation here: #346 
I am now completely stuck.

When I open the page under http://app.respondcms.lo/sites/my-site I only get a white page.
First I thought I just have to create a page first, but when I was in the admin, I realized there is already content added.
I went to http://app.respondcms.localhost/#/app/configure to change the theme, but the issue is with all themes.

The console is full with errors saying "Uncaught SyntaxError: Unexpected token <", which sadly doesn't help me at all to find the issue.

I can provide you with some screenshots and if you think it would help, I could also localtunnel.me.

![screen shot 2015-10-25 at 14 57 24](https://cloud.githubusercontent.com/assets/694883/10714412/cab794d0-7b29-11e5-878a-62406640a5b4.png)
![screen shot 2015-10-25 at 14 57 32](https://cloud.githubusercontent.com/assets/694883/10714413/caba286c-7b29-11e5-89c0-b8169db9a7f3.png)

**Comment by joebordes** [comment]
Try changing the URL_MODE to HTML5

https://github.com/madoublet/respond/blob/master/setup.php#L83

and also have a look at this thread from the email group:

https://groups.google.com/d/topic/respond-cms/WVlAX431vsA/discussion

**Comment by n3ssi3** [comment]
Thank you for the fast reply.
I tried that already, but then I got an error about $location/nobase... I found this https://docs.angularjs.org/error/$location/nobase and added the tag.

After adding the tag, again I get the "Uncaught SyntaxError: Unexpected token <"

**Comment by madoublet** [comment]
Are you seeing any errors on the test page? (e.g. https://demo.respondcms.com/test/)

**Comment by madoublet** [comment]
If the respond.libs.min.js is returning HTML then there is something not working correctly with mod_rewrite.  This should return compressed JS.

**Comment by n3ssi3** [comment]
Cool thanks https://demo.respondcms.com/test/ helped a lot.
The directory sites/mysite was not writable.

Maybe add the link to the test page also to the Installation page (http://respondcms.com/documentation/installation)?
