### ISSUE TITLE
Any plan for providing nginx installation guide?

### ISSUE THREAD

**Issue by timwangdev** [madoublet/respond#350]
For users who prefer hosting respond with nginx + php-fpm.

And  any recommend URL rewrite config documents for nginx would be better.

**Comment by d9k** [comment]
please, we crave it!

**Comment by axis80** [comment]
There have been a lot of discussions on the mailing list about nginx.  I think some people have successfully gotten it running.  See https://groups.google.com/forum/#!searchin/respond-cms/nginx

Would one of you be able to look through those discussions, and condense them into some setup instructions?  If you will paste them into this issue report I will make sure they get added to the online documentation.
