### ISSUE TITLE
Authorization issues on installation

### ISSUE THREAD

**Issue by edinchez** [madoublet/respond#363]
After spending ages configuring my MAMP environment, I finally got the themes to show up in the installation process. Now after submitting the installation form I'm getting [these errors](http://i.imgur.com/TFNpHBU.png) in the console. 

The URL also looks weird: http://respond.localhost/#/login/undefined 

I tried doing [this](http://stackoverflow.com/questions/18424055/authorization-header-and-apache-request-headers-function) from the [Solutions page](http://respondcms.com/documentation/solutions) without any luck. Or I might be doing it wrong. I tried including the code

`<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>`

in the httpd.conf file and also the .htaccess file without any luck. I also tried removing the if statement from the .htaccess file without any luck.

Is there anything I'm doing wrong?

**Comment by semeano** [comment]
@edinchez what happens if you go to http://respond.localhost/api/site/test ?
