### ISSUE TITLE
Where to activate Single Page Application Mode?

### ISSUE THREAD

**Issue by smith64fx** [madoublet/respond#364]
Hello there!

First of all, I really love RespondCMS and I like to replace Wordpress with it!
One thing I am currently wondering about is: How can I make the pages in the frontend working like a single page application?

In the backend the content is switched using UI-Router without reloading the page. But in the frontend all the pages are loaded static when I switch to another site. So it's not really a single page application.

> Static and HTML5 mode URLs for sites.  The static URL mode makes your Angular sites fully searchable by any search engine.  While the HTML5 mode enables push-state based navigation (powered by AngularJS UI-Router extension) for app-like website performance.

Did I miss out something or is there any way to use UI-Router in the frontend? Or is there a way to fetch just the content of a site from the backend?

Thank you very much in advance!

Best regards,
Michael

**Comment by madoublet** [comment]
Sorry, this is no longer available.

**Comment by smith64fx** [comment]
Is there a reason why you have deactivated this feature?

**Comment by madoublet** [comment]
It was complicated to support both modes and the future of Angular 1.4+ was uncertain.  So, I migrated the plugin system from Angular directives to Polymer web components and removed the dependency on Angular for sites.
