### ISSUE TITLE
Workflow for theme development

### ISSUE THREAD

**Issue by pkaske** [madoublet/respond#365]
Hi there,

Response looks very promising to me and the fact that it works with Polymer is awesome. The only think I'm struggling is the workflow to develop a theme. Can you give some inside how you develop themes for the system. The docs seem to be very short on this topic.

Thank you!

**Comment by madoublet** [comment]
The easiest way is to duplicate an existing theme and update the .json configuration file.  When you are working on a theme, you need to republish the system files after every update.
