### ISSUE TITLE
Restore site instance from backup?

### ISSUE THREAD

**Issue by destinationdesigns** [madoublet/respond#372]
I need to know if it possible and how to restore a site instance from a backup. It seams if i just drop the backed up files and directories into the app/sites directory, it does not recognize the files in the application. Is this because it is taking what is seen in the application from the "pages" database table rather than from the html file itself?

I really need to get this site back up and running as soon as possible, so any help would be appreciated.

**Comment by AndryBray** [comment]
I think you should backup your database data as well.
As I can see, respond reads the site from db
