### ISSUE TITLE
ApplyStyleAttributes bug

### ISSUE THREAD

**Issue by AndryBray** [madoublet/respond#374]
Saving some page I see notice
Notice: Undefined variable: imagesURL in /var/www/html/mysite/app/api/libs/Publish.php on line 1442 Fatal error: Call to a member function find() on a non-object in /var/www/html/mysite/app/api/libs/Publish.php on line 1262

and I found you are trying to set `$backgroundimage = $imagesURL.$el->backgroundimage;`
but  `$imagesURL` is not declared.

Possible bug fix:
pass `$site` to every `ApplyStyleAttributes` call and replace
```
// public static function ApplyStyleAttributes($html){
public static function ApplyStyleAttributes($html, $site){
     $imagesURL = $site['Domain'].'/';
```

**Comment by axis80** [comment]
Fixed in the dev branch.  Thanks very much for the report, and for including a fix along with it!
