### ISSUE TITLE
Page editor bug: table class is not saved

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#376]
It is possible to assign a CSS class to a table, but it does not persist after you click Save & Publish.

Steps to reproduce:

1. Drag a table onto the page.

2. Click anywhere in the table, then enter a custom CSS class in the config field to the right.

3. Click Save and Publish.

4. Reload the page.  You'll see that the class field has changed to `table table-striped table-bordered col-2` .  Your custom class is nowhere to be found.

**Comment by axis80** [comment]
Fixed in dev branch by commit 7f804a9fed49571ef008a4cdf53c964ba3fe6035 .  I would feel better if someone smarter than me reviewed this before I also apply the commit to the master branch.  I am pretty much a noob with Angular and sort of fumbled my way through the fix.  Matt?  Joe?

**Comment by joebordes** [comment]
Looks good to me.
