### ISSUE TITLE
bug: Shelf undefined

### ISSUE THREAD

**Issue by trakons** [madoublet/respond#380]
![screen shot 2016-01-20 at 11 21 56](https://cloud.githubusercontent.com/assets/3083964/12446424/2f72ade0-bf6a-11e5-9b34-010305213e47.png)

I don't know why, before the price is writed "undefined"
I have tried to reinstall and reconfigure the cms many times.

**Comment by Maximumz** [comment]
This had been adressed & a pull request was made & merged to the dev branch of RespondCMS

**Comment by trakons** [comment]
Okay, in the dev branch is working correctly
