### ISSUE TITLE
Vulnerability: hack item price

### ISSUE THREAD

**Issue by trakons** [madoublet/respond#381]
![screen shot 2016-01-20 at 11 53 44](https://cloud.githubusercontent.com/assets/3083964/12446841/b787b8b8-bf6c-11e5-80e7-8b1dca2f01f0.png)
You can modify the "price" attribute of "respond-shelf-item" for change the item price.
Please fix this issue

**Comment by axis80** [comment]
@trakons, do you have any suggestions as to the best way to fix the issue?  That would speed along its resolution.

**Comment by trakons** [comment]
Here is an example of how to add items to the basket
![drawing5](https://cloud.githubusercontent.com/assets/3083964/12575692/df72d99c-c40e-11e5-8f04-1dd2745e759d.jpg)
The client know only the ITEM ID, all item details is in the database

**Comment by neoalienson** [comment]
Please label it as a bug
