### ISSUE TITLE
Direct URI translation

### ISSUE THREAD

**Issue by AndryBray** [madoublet/respond#385]
Hello,
is there any way to access directly inside the translated page without cookies/language selection?

More, how does Google crawlers will treat the translation of websites? As long as it uses ajax with cookies, will Google be able to index everything?

Thank you

**Comment by AndryBray** [comment]
@axis80 do you know it there is a way to accomplish this?

**Comment by axis80** [comment]
No, I don't know the answer to your first question.

Regarding the second question:  I have read in the past about how Google handles multi-language sites, and I remember it being sort of complicated.  IIRC there are meta tags you can add that will specify the language in use.  And, you can also add attributes to divs on the page to indicate which language they're in, if there are multiple languages mixed together.  

I don't know whether Google will be able to find the translated version of your site.  If you learn anything about this I would be curious to hear your findings, and whether any additional meta tags are needed to make multi-language Respond sites more indexable.

**Comment by AndryBray** [comment]
Thank you. I know that Google indexes ajax content loading but of course this would be a problem if the content are related to cookies and similar "tricks".

I think the best way is to build the same tree files structure of original language under the language folder.
Something like "es/my-spanish-index.html" then, add some check on the first uri to let respond use cookies with the right language or something like that.

I will give a deep look at this and we will see what will come out =)
