### ISSUE TITLE
Windows Edge browser polymer errors

### ISSUE THREAD

**Issue by AndryBray** [madoublet/respond#387]
Hello @axis80 @madoublet 
I'm testing respondcms over Windows Edge and I get a lot of errors like `DuplicateDefinitionError - Already registered (Polymer) for element respond-fetch/comments/(and all the other components)`.

The site is blocked or very slow (like in a loop)

Is this a polymer version problem?
Please, let me know if you know this issue. I will try to update webcomponent-lib to check if this has been fixed.
Thank you

**Comment by axis80** [comment]
Try the dev branch - that uses a more recent version of Polymer that
addresses a lot of Windows Edge issues

**Comment by AndryBray** [comment]
Just tested. Same problems... anyway it looks like the versions are the same.
Any other solution?

**Comment by axis80** [comment]
Have you tried a hard reset of your browser cache, to make sure it is
loading the new dev versions of the Polymer and web components libs?

**Comment by AndryBray** [comment]
Ok, it was just cache. Thank you, the new version has fixes for edge.

**Comment by AndryBray** [comment]
PS: it seems to work..but when I reload the browser will freeze. Do you have opportunity to test it?

Just load a respond site (notion theme) after first loading, reload the page and it will block

**Comment by axis80** [comment]
I don't have a machine w the Edge browser. I will have to depend on you and
others for any further debugging.

**Comment by AndryBray** [comment]
I'm just trying to reset the theme because I have some custom plugin, maybe it's related to this. I will let you know. Thank you

**Comment by AndryBray** [comment]
Fixed: I forgot to rebuild my plugins with the new version of webcomponent...

**Comment by axis80** [comment]
This fix is now available in version 5.3 that Matt released the other day.  Closing this issue.
