### ISSUE TITLE
Page automatic thumbnail broken when page only contains external images

### ISSUE THREAD

**Issue by ECoursimault** [madoublet/respond#390]
I'm using only exernal URL image when building a page. As a result, the backend automatic thumbnail is broken (although the page images are displayed fine on frontend). Am I missing something? Thanks.

![pagethumbnail](https://cloud.githubusercontent.com/assets/5838118/13256009/2a8ce22e-da49-11e5-93c7-5e481a506032.png)

**Comment by madoublet** [comment]
Closing issues not related to R6.
