### ISSUE TITLE
Date/Time type input in plugin config (editor ng-model bug)

### ISSUE THREAD

**Issue by AndryBray** [madoublet/respond#391]
Hello,
there is a bug trying to create an input type=date inside the config html file for a custom plugin.

**Step to reproduce:**
- Create a custom plugin
- Put inside the config.html a field like this:
```
<div class="form-group">
	<label for="enddate">{{'End Date' | i18next}}</label>
	<input id="enddate"
		ng-model="node.enddate"
		type="date" class="form-control">
</div>
```
- Map the field inside the js config file (where you have create/parse/config methods)
- Reload everything
- Drag & drop the plugin inside the editor
- Select it, and select a new date from the contextual menu
- Save and reload
- Select again the plugin (this one saved inside the editor)
- Here the field (input date) should load your previous selected date but there is an error: `Error: ngModel:datefmt - Model is not a date object`

This happens because inside the `respond.editor.js` you didn't check about Date type as ng-model.

**The bugfix:**
add the code above to `respond.editor.js` - L705
```
//you have to set a node with "ngdate" or "ngtime" as part of the name to be recognized as date
//add support for Date ng-model (attributes with ngdate/time part as name)
//excluding important keys as "id" and "class"
//check on length as Date.toString produces smt like "Fri Feb 26 2016 00:00:00 GMT+0700 (CET)"
if(key != 'id' && key != 'class' && value && value !== '' && value.length >= 30 && (key.match('ngdate') !== null || key.match('ngtime') !== null)) {
	try {
		var isDate = new Date(value);
		if(typeof isDate !== 'undefined' && isDate != null && isDate !== 'Invalid Date' && isDate instanceof Date && typeof isDate.getMonth === 'function') {
			value = isDate;
		}
	} catch(e) {
		console.warn("error checking Date format in respond.editor")
	}
}
```

of course with this patch every node which uses date or time field must use a "ngdate" or "ngtime" part inside of the name. eg. (node.ngdatestart)

**Comment by madoublet** [comment]
Closing issues not related to R6.
