### ISSUE TITLE
Editor <a> click event fired for "non action" links

### ISSUE THREAD

**Issue by AndryBray** [madoublet/respond#392]
Hello, when I use the editor very often I see many errors of `Uncaught TypeError: Cannot read property 'create' of undefined` utilities.js line 425.

I see this is caused by the click event over the Flipsnap buttons/arrows of the toolbar.

My bugfix is to add this check inside the `respond.editor.js`

```
// handle click/dragstop
    $('#editor-menu').on('dragstop click', '.editor-menu a', function(){
       
        //skip link/tabs/Flipsnap arrows click
    	if($(this).attr('data-action') == null) {
    		return;
    	}

   //...
```

**Comment by AndryBray** [comment]
The same for the "REMOVE" link/button on the sidebar.

```
// setup text events
  $(document).on('mousedown touchstart', '.context-menu a', function(e){
           if($(this).attr('data-action') == null) {
            return;
        }
...
```

**Comment by axis80** [comment]
@AndryBray , you have been submitting a lot of very useful bug fixes.  Would it be possible for you to submit them as pull requests, made against the dev branch?  If you can do that, it will make it much easier for us to include your fixes into the main codebase.  It becomes a matter of one of us clicking "accept".

How to create a pull request: https://github.com/PointCloudLibrary/pcl/wiki/A-step-by-step-guide-on-preparing-and-submitting-a-pull-request

If pull requests are not possible I will merge in the fixes manually.  I am grateful to you for sending them in whatever form you can.  But, it will take longer for me to find the time to merge them manually.

**Comment by AndryBray** [comment]
@axis80 I will try to setup a fork for next bug fixes.
In the meantime, please  fix it in the main dev branch (I really can't do it right now). Thank you

**Comment by madoublet** [comment]
Closing issues not related to R6.
