### ISSUE TITLE
Settings / Payments / Tax Rate not saved as expected

### ISSUE THREAD

**Issue by AndryBray** [madoublet/respond#394]
Trying to save the tax rate value to "22" I see it saves always "0.99999" on DB

**Comment by AndryBray** [comment]
FIXED (database problem):
run this query

```
ALTER TABLE  `Sites` CHANGE  `TaxRate`  `TaxRate` DECIMAL( 10, 5 ) NOT NULL DEFAULT  '0.00000'
```

**Comment by AndryBray** [comment]
I've just realized that Tax Rate has been intended as decimal number... honestly as first impression I though it was the % rate, so I was trying to insert 22 (%) instead of 0.22.

I'm gonna changing anyway the respond-cart calculation from 
```
this.tax =  this.subtotal * this.taxRate;
```

to 

```
this.tax =  (this.subtotal * this.taxRate)/100;
```

This because IMO is more intuitive than asking for decimal rate.

**Comment by axis80** [comment]
I see your point, but this would break existing sites.  I am inclined to leave it as-is and just add more clear labeling to the input field.

**Comment by madoublet** [comment]
Closing issues not related to R6.
