### ISSUE TITLE
respond-cart taxRate wrong override

### ISSUE THREAD

**Issue by AndryBray** [madoublet/respond#395]
There is a bug on respond-cart.html component at line # 353 which will break tax calculation on cart.

``` 
this.taxRate = 0;
```
this line overrides `this.taxRate` set before on line # 320 `this.taxRate = parseFloat(respond.site.settings.TaxRate);`

BUGFIX: remove line # 353

**Comment by madoublet** [comment]
Closing issues not related to R6.
