### ISSUE TITLE
Page URL add / rename needs unique check

### ISSUE THREAD

**Issue by AndryBray** [madoublet/respond#396]
Hello,
I think the `IsFriendlyIdUnique` should be called even on every page adding/editing.

In fact, if you try to create the pages with URL `url-1` and `url-2`, changing `url-1` into `url-2` the publish process will override the `url-2` with content from `url-1` loosing every relation.

More.. if you rename the url from `url-2` into `url-3`, I see the `url-2.html` will still exist under the site folder, and the worst, it's accessible from browser, so we'll have 2 identical pages but with different url.

**Comment by madoublet** [comment]
Closing issues not related to R6.
