### ISSUE TITLE
README not updated for 5.3 release

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#400]
This is a question for @madoublet and @joebordes .

When 5.3 was released, the README was not bumped to reflect the new version number.  So, when people land on the main github repo page it shows that the current version is 5.2.

I've update the README with the correct information, in this commit: 93298e2b7369c801087761679c85e68d08b3dd09

However, I'm unsure of the process you want me to follow for getting that change into the master branch.  I would approach it by checking out the master branch, typing `git cherry-pick 93298e2b7369c801087761679c85e68d08b3dd09` and then committing and pushing the change up to master.

Is it OK if I do that, or do you prefer that I take a different approach / not update it?

If you haven't told me otherwise by 15 March, I'll proceed as proposed above.

**Comment by msmithehi** [comment]
I am fine with your approach.

**Comment by madoublet** [comment]
I am fine with your approach.

**Comment by axis80** [comment]
Done.  Thanks for the fast reply, Matt.
