### ISSUE TITLE
getting Problem in Installation

### ISSUE THREAD

**Issue by GaneshKandu** [madoublet/respond#405]
Hi, am Installing "Respond CMS 5.3" but getting Problem in Installation
Installing in Sub-Folder

![screenshot-192 168 1 191 2016-03-09 12-17-03](https://cloud.githubusercontent.com/assets/12833130/13627526/f6369156-e5f0-11e5-9787-2b98f71b338f.png)

unable to proceed and Getting 404 for api/theme
 Getting 404 error for all js and css

![dgf](https://cloud.githubusercontent.com/assets/12833130/13629388/ccf819dc-e5fe-11e5-9be7-3584880ab479.png)
Installing in Sub Directory But Respond CMS Looking in Root of Web Directory

**Comment by madoublet** [comment]
This is not a bug in the software.  You most likely do not have mod_rewrite configured properly.  Please refer to the forums for help.

**Comment by GaneshKandu** [comment]
Hi, I Have tested mod_rewrite on my machine and its working very well 
[http://www.workingwith.me.uk/articles/scripting/mod_rewrite](http://www.workingwith.me.uk/articles/scripting/mod_rewrite)
```php
	/*********************************/
	/*  BASIC SETUP                  */
	/*********************************/

	// DB connection parameters
	define('DB_HOST', '{{host}}');
	define('DB_NAME', '{{database}}');
	define('DB_USER', '{{db usre}}');
	define('DB_PASSWORD', '{{db pass}}');

	// If not set, we figure it out baded on the HTTP request.
    define('APP_URL', 'http://{{ip}}/respond');
```
I did same what you mentioned on 
[http://respondcms.com/documentation/installation](http://respondcms.com/documentation/installation)
and i am giving recursively writable to my whole respond installation directory 
i have mcrypt, gd, and curl extenstions
and GIT Installed
php 5.4

running on Apache/2.2.31 (Unix)

**Comment by madoublet** [comment]
There is a test suite installed with Respond that helps you troubleshoot common issues at http://my-respond-installation.com/test.  You can see a successful test on the demo below:

https://demo.respondcms.com/test/

**Comment by GaneshKandu** [comment]
Hi, Thanks to reply
Now its working  :+1: :smile:
