### ISSUE TITLE
Docker readme out of date

### ISSUE THREAD

**Issue by maxengel** [madoublet/respond#406]
The link to "Volumes" is broken.

Also, it is unclear if I need to run:

$ DATA_DIR=${HOME}/respond-data
$ mkdir -p ${DATA_DIR}/sites 
$ mkdir -p ${DATA_DIR}/mysql

**Comment by axis80** [comment]
I am not familiar with Docker.  @chirino , you initially submitted the pull requests that added Docker support.  Can you point us in the right direction on this?

**Comment by neoalienson** [comment]
The commands are required if you want to store content in /app/sites and /var/lib/mysql to your docker host instead of storing inside the docker image.

**Comment by neoalienson** [comment]
#411 for fixing the broken link and adding more details

**Comment by madoublet** [comment]
Closing issues not related to R6.
