### ISSUE TITLE
No login possible

### ISSUE THREAD

**Issue by AlexR089** [madoublet/respond#410]
Hey,

I just started with response and really liked the demo so I wanted to give it a go.

I tested this with two different web hosters but can't get it to run properly.
Current hosting company is "Strato".
All respond installation tests are ok / passed.

If I want to create a site, the theme selection wont show up. I do have the left / right arrows but no Theme get's previewed. 
You can still create a page but if I try to login with the previously set account informations all I get is a loading screen.
Firebug console got me this error:

```
Error: data.user is undefined
$scope.login/<@http://app.stoffizwerge.de/js/respond.controllers.js:1932:1
k/g.success/<@http://app.stoffizwerge.de/js/respond.libs.min.js:86:26
f/<@http://app.stoffizwerge.de/js/respond.libs.min.js:119:302
hf/this.$get</m.prototype.$eval@http://app.stoffizwerge.de/js/respond.libs.min.js:134:79
hf/this.$get</m.prototype.$digest@http://app.stoffizwerge.de/js/respond.libs.min.js:131:98
hf/this.$get</m.prototype.$apply@http://app.stoffizwerge.de/js/respond.libs.min.js:134:359
l@http://app.stoffizwerge.de/js/respond.libs.min.js:86:325
M@http://app.stoffizwerge.de/js/respond.libs.min.js:90:370
Rf/</x.onload@http://app.stoffizwerge.de/js/respond.libs.min.js:91:394

http://app.stoffizwerge.de/js/respond.libs.min.js
Line 107
```

And chrome got me this error:

```
respond.libs.min.js:107TypeError: Cannot read property 'CanEdit' of undefined
    at respond.controllers.js:1932
    at respond.libs.min.js:86
    at respond.libs.min.js:119
    at m.$eval (respond.libs.min.js:134)
    at m.$digest (respond.libs.min.js:131)
    at m.$apply (respond.libs.min.js:134)
    at l (respond.libs.min.js:86)
    at M (respond.libs.min.js:90)
    at XMLHttpRequest.x.onload (respond.libs.min.js:91)
```

Any help is appreciated :)

Thanks,
Alex

**Comment by axis80** [comment]
The behavior of "left / right errors but no theme showing up" is pretty common, but I don't personally remember what the fix is.  I think it may have something to do with mod_rewrite not being installed, but I'm not sure.  I suggest posting this to the Google Groups forum.  People there run into this all the time and should be able to help you get it straightened out quickly.

**Comment by madoublet** [comment]
It looks like the theme selection is now showing up.  Were you able to fix the problem?

**Comment by neoalienson** [comment]
Another possibility is setup.php got overwrite by checking out the source which I have just encountered, which result below error from /api/user/login when login

[Site::GetDomains] PDO Error: SQLSTATE[28000] [1045] Access denied for user 'dbuser'@'localhost' (using password: YES)

**Comment by AlexR089** [comment]
Ok guys,

first of all, thanks for the quick reply. 
I was on a business trip over the last few weeks and couldn't work on the site until now.
Somehow it seems to work now, I didn't change anything but perhaps .htaccess changes will only be applied over night at my hoster.
Anyway, problem seems fixed :)
Thanks again!

Cheers,
Alex
