### ISSUE TITLE
Site iframe in admin console requesting insecure site

### ISSUE THREAD

**Issue by tikenn** [madoublet/respond#421]
I have my respondcms on a web server behind a reverse proxy in a LAN.  The connection from the user to the reverse proxy is secured with SSL, but the reverse proxy to web server connection is not.  I forward headers from the reverse proxy, but the site iframe in the admin console area used for modifying/changing a theme still requests the insecure version of the site.  As a result, the site doesn't display in the iframe unless the browser is instructed to stop blocking of the insecure content.

**Comment by madoublet** [comment]
Closing issues not related to R6.
