### ISSUE TITLE
Share component not working on pages included with list component on FF and IE

### ISSUE THREAD

**Issue by gbollen** [madoublet/respond#423]
This can be easily be reproduced on a demo site. For example if I add the share component to a post, it shows fine on the post page. But on the blog page (where the posts are loaded through the list component), the share component is not working properly. Facebook button is not loading.
This is an issue on Firefox (tested on 45.0.2) and Edge (13 on Windows 10).

In addition the Tweet button is not loading any graphics on Firefox and IE/Edge.

**Comment by madoublet** [comment]
Closing issues not related to R6.
