### ISSUE TITLE
I met this issue, what happened about initiating?

### ISSUE THREAD

**Issue by elton0895** [madoublet/respond#424]
Hi MATTHEW,

![image](https://cloud.githubusercontent.com/assets/7447537/14557752/56887f44-0331-11e6-87b1-6eaf6dc161c6.png)

I met this issue, what happened about initiating?

**Comment by axis80** [comment]
It looks like there is a problem connecting to the MySQL database.  Double check your database config settings, and make sure you have loaded the schema.sql.  Also try changing the hostname from localhost to 127.0.0.1.  More suggestions here: http://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory

**Comment by elton0895** [comment]
@axis80 ,thanks a lot! it seems like you said, database setup.php issue

**Comment by elton0895** [comment]
@madoublet hey Matt, last time I solve the issue in my local environment, but it happened again when I do the same whole thing in AWS-ubuntu, 
![image](https://cloud.githubusercontent.com/assets/7447537/14731224/f83ad554-0880-11e6-8cee-0072d6a02aee.png)
![image](https://cloud.githubusercontent.com/assets/7447537/14731230/00977680-0881-11e6-98ee-cae35b348cbd.png)

i am sure that i followed your guide.

**Comment by madoublet** [comment]
Closing issues not related to R6.
