### ISSUE TITLE
Unexpected token < setup.js.php: 1

### ISSUE THREAD

**Issue by ramorris3** [madoublet/respond#425]
Hi all,

I'm completely stuck.  I'm trying to run respondcms on a local Apache server on Ubuntu 14.04 LTS.  When I go to the main app page (the site creation page) at localhost/app, I get a blank screen and some console errors.  

![respond](https://cloud.githubusercontent.com/assets/7407619/14584866/3106730e-041a-11e6-918a-c1b7ad4e7818.png)

It looks very similar to #347, but it's happening in the root folder rather than in the sites folder.  I followed all the advice in #347 and here: https://groups.google.com/d/topic/respond-cms/WVlAX431vsA/discussion but I'm not having any luck.

I'm not sure why the `<?php` at the beginning of setup.js.php is fouling things up.  Oh, also, when I go to the test page (localhost/app/test), I get this:

![respond-test](https://cloud.githubusercontent.com/assets/7407619/14584884/bc87d6d4-041a-11e6-8236-87dd0475e8d9.png)

Not really sure what's messing that up...

Thanks in advance

**Comment by axis80** [comment]
Are you sure that mod_php is even installed on your server?  It looks like
it is not.  I can tell you for sure that Respond will run on Ubuntu 14.04
LTS, as I have several instances of it running on that version.

**Comment by ramorris3** [comment]
Not sure how I missed that.  Thanks so much for the quick response!

**Comment by axis80** [comment]
Glad to help.  Good luck with the rest of the installation!

**Comment by ramorris3** [comment]
Sorry to bug you again... So now I'm getting a problem connecting to the API.  It's giving me a 404 error, which means MOD_REWRITE is most likely not enabled.  But when I type `a2enmod rewrite` it says `Module rewrite already enabled`  Is there any other reason respondcms would have trouble connecting to API?

**Comment by ramorris3** [comment]
It turns out I was also missing pdo_mysql... But it's up and running now. Sorry for bugging you about unrelated config questions!  Thanks again!

**Comment by axis80** [comment]
OK, glad you got it!

BTW, note that the Google Group can be a good resource.  There are a lot of people there who will pitch in to help others figure out setup issues like these.
