### ISSUE TITLE
Avoid hardcoded host names and protocol

### ISSUE THREAD

**Issue by aheintz** [madoublet/respond#426]
I've installed respond cms and it took quite a while and quite some struggling to do it. Mostly because I cannot install it using the "real" host/domain, secondly because I'm serving the site behind a reverse proxy (on another port than port 80) and third since we serve content over https.

I think Respond cms looks promising, but the setup is based on a few not well thought-through things:

1. When creating a product, you should never generate absolute URL:s with host/domain and protocol. Relative url's are the shit. Will also allow you users to serve the site using any port number.
2. Never, ever link to external CDN items using "http". Instead use https or more preferrably on the format "//your.cdn.com/resource.css". This approach will allow the browser to use http or https depending on the current protocol. Using "http://" if the site is using https will be prevented by most browsers.

**Comment by neoalienson** [comment]
Thanks for the comments. We have merged pull request #409 into dev branch for replacing 'http and https' with // for resources. Assume comment 2 it is resolved.

We should mark this as a bug as it prevent the application working when port is supplied in URL.

**Comment by madoublet** [comment]
Closing issues not related to R6.
