### ISSUE TITLE
Images not showing when uploaded through the respond admin interface

### ISSUE THREAD

**Issue by trevorlazarus** [madoublet/respond#427]
Hi, Thanks for the neat project, I set it up using Docker on a Google Compute Engine VM  instance, but I'm not able to upload images e.g. under the branding section of the admin interface. Is there a way to fix this?

**Comment by axis80** [comment]
Do the images upload correctly on the Files admin screen?

**Comment by madoublet** [comment]
Closing issues not related to R6.
