### ISSUE TITLE
Less support

### ISSUE THREAD

**Issue by AndryBray** [madoublet/respond#436]
On previous version Less was really important during the theme building process.
Looking at the new theme schema I suppose there is no way to use less (built-in feat.)

**Comment by madoublet** [comment]
With Respond 6, I looked at integrating LESS into the build process.  It is certainly possible.  However, I felt like Gulp (or similar automation tool) was a much better way to handle this.  This allows you to use SASS or CSSNEXT or whatever comes next.  I felt like Respond 5 was way too opinionated on how to write CSS.  I did not want to repeat that in Respond 6.

**Comment by AndryBray** [comment]
Do you plan to support theme settings? It was very good feature because of possibility to map parameters for every theme (now the user can't select colors, font, etc.)

**Comment by madoublet** [comment]
Yes, I think theme settings (or setting a value in the CSS) would be awesome.  I really want to be able to do this within the settings.json file itself.  So, there would be a single place to do all the settings for a theme.

https://github.com/madoublet/respond/blob/master/public/themes/bootstrap/private/settings.json

**Comment by AndryBray** [comment]
Yes, I mean settings as it was before inside theme configurator (sidebar with colorpickers) where the user could change the compiled css (merging settings & sass code)

**Comment by madoublet** [comment]
Same concept, but it would all be merged into the settings UI so that you can change your branding and colors in one spot.

**Comment by destinationdesigns** [comment]
Just a note, when Bootstrap releases v4 they are dropping support for LESS and will be 100% SASS. I'm not a big fan of this as I know LESS and having to learn something new is a PITA. But I agree with Matt in that limiting to one compiler closes a lot of development doors.
