### ISSUE TITLE
Site i18n

### ISSUE THREAD

**Issue by AndryBray** [madoublet/respond#437]
At the moment the only way to translate is to build a new page and writing again all.
Do you plan a tool to translate inside editor (1 page - multiple lang contents)?

**Comment by madoublet** [comment]
Good question.  I am not sure.  Respond 6 does not prevent you from implementing this, but it is not built in.  I implemented a few multi-lingual sites and I never used in-page translations b/c they did not work well with SEO or multi-language tags.  https://support.google.com/webmasters/answer/189077?hl=en
