### ISSUE TITLE
Opening a gitter

### ISSUE THREAD

**Issue by graknol** [madoublet/respond#445]
Opening a gitter channel for Respond would be immensely helpful and give a central location for everyone to chat about all things Respond.

**Comment by graknol** [comment]
This came to my head as I wondered about if this framework still uses polymer (couldn't find traces of any). Even simple questions like that would be appropriate for a gitter channel.

**Comment by madoublet** [comment]
This is done:  https://gitter.im/respondcms/Lobby  I also added it to the help: https://respondcms.com/help
