### ISSUE TITLE
2 sites get created

### ISSUE THREAD

**Issue by graknol** [madoublet/respond#446]
When creating a new site 'foo', another site named 'foo1' gets created.

EDIT: This only happens on **Windows**, I tried it on Ubuntu and it works as expected

**Comment by madoublet** [comment]
If you have a duplicate in resources/sites or public/sites, it will auto-increment the ID (e.g foo1, foo2, ...).  Deleting the folders in these locations (e.g. resource/sites/foo and public/sites/foo) will free up that ID to be used again.

**Comment by graknol** [comment]
@madoublet yes I know that, but this happens when the folders are empty

**Comment by madoublet** [comment]
Did you figure out what was happening?

**Comment by graknol** [comment]
No, not under wamp, but seeing that respond doesn't fully work unless in a linux environment, I deemed it a non-issue.
