### ISSUE TITLE
Doubt: Multi Language and One Site

### ISSUE THREAD

**Issue by boing6000** [madoublet/respond#449]
How to proceed to create a multi language site and have in the mysite.com

**Comment by madoublet** [comment]
You can create multiple routes, e.g.:

mysite.com/en
mysite.com/fr

**Comment by boing6000** [comment]
Ok, and how to point the sites/site to / in my domain.

**Comment by madoublet** [comment]
It depends on your setup, but this is how you do it with Apache VirtualHost: 
https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-14-04-lts

**Comment by boing6000** [comment]
I don't have access in my host, i have just access to edit dns zones and create subdomains, is possible to use .htaccess?

Another thing in the final release this new version will have the ability to change colors end others theme options like in the old version?

**Comment by madoublet** [comment]
I am not sure.  It really depends on your setup.  In the current version, you can change images.  You will be able to change colors in a future beta.  But, I don't plan on providing as many theme options as before.

**Comment by boing6000** [comment]
Thank you for your help.

**Comment by madoublet** [comment]
No problem.  I created an issue to track setting colors from settings.  https://github.com/madoublet/respond/issues/450
