### ISSUE TITLE
Unable to edit newly created pages

### ISSUE THREAD

**Issue by raqu3l** [madoublet/respond#453]
Clicking "Edit" on newly created pages gives me this browser error "FatalErrorException in EditController.php line 60: Call to a member function setAttribute() on a non-object". 

On the demo site, it shows me a blank page.

**Comment by madoublet** [comment]
I will take a look and see what is going on.

**Comment by madoublet** [comment]
What theme is this?  Material?  I think the .default.html file is missing from the theme.  I will add that.

**Comment by madoublet** [comment]
Let me know if this fixes it.

**Comment by raqu3l** [comment]
It was the Material theme. This fixed it, thanks!
