### ISSUE TITLE
Its not possible to upload any file after update to RC5

### ISSUE THREAD

**Issue by DTX-92** [madoublet/respond#455]
There is no Plus button in files section.
![image](https://cloud.githubusercontent.com/assets/20479161/18069644/3311d7b4-6e51-11e6-999e-8660bc2ff43c.png)

**Comment by madoublet** [comment]
Thanks!  Not sure what is going on.  I am guessing it was related to the component changes in RC5.  It looks like the file uploader is missing from galleries as well.  I will investigate and issue a fix soon.

**Comment by madoublet** [comment]
Should be fixed now.

**Comment by axis80** [comment]
Confirmed fixed in RC2 branch.
