### ISSUE TITLE
Call to undefined method App\Respond\Models\Site::saveUser()

### ISSUE THREAD

**Issue by DTX-92** [madoublet/respond#458]
I was trying to recover password.
![image](https://cloud.githubusercontent.com/assets/20479161/18088401/133f6786-6ec3-11e6-8581-1caa72240358.png)

**Comment by madoublet** [comment]
Thanks, I will get this fixed.

**Comment by madoublet** [comment]
Should be fixed now.  I need to do some more end-to-end testing around this functionality.  But, this specific bug is fixed.
