### ISSUE TITLE
Divide css on core.ss and theme.css

### ISSUE THREAD

**Issue by DTX-92** [madoublet/respond#464]
I want to remove bootstrap styles and add my own, but i cant delete site.min.css, because there are some core style for lighbox and etc

**Comment by madoublet** [comment]
In general, Respond has no opinion on how you structure your CSS.  For default themes, I keep all styles in site.css and then use gulp to combine that with all other dependencies to produce site.min.css.  This keeps the core CSS simple while packaging everything nicely for production.  I have documented the Gulp recipes here:  https://respondcms.com/documentation/gulp-recipes

**Comment by DTX-92** [comment]
Got it. 
libs.min.css
and
plugins.css
saved me. Thx!
