### ISSUE TITLE
v6 HTML element

### ISSUE THREAD

**Issue by destinationdesigns** [madoublet/respond#466]
In v5 we could create a custom HTML element, this was useful for creating custom buttons for things like launching modals ect... Also, the text editor used to have the option to insert favicons or icons. This seems to be missing as well, and without a way to insert raw HTML in the editor, there is no way to do this.

**Comment by madoublet** [comment]
I am inclined to enable editing the innerHTML of existing elements versus a new HTML element.  But, I will look at both scenarios.

**Comment by destinationdesigns** [comment]
Thinking about this, it could be as simple as having an HTML editor option for the page vs the element. I feel like this is pretty common in most CMS editors.

**Comment by madoublet** [comment]
Working on an HTML editable option for the page.  But, the HTML element is now in RC1.
