### ISSUE TITLE
Support for bootstrap snippets?

### ISSUE THREAD

**Issue by Rubytastic2** [madoublet/respond#480]
Very great project, 
have been looking for something like this.

Would it be possible to create support for bootstrap components?
Carousel , etc?

**Comment by madoublet** [comment]
Thank you!  I do use the Bootstrap Carousel for the slideshow plugin in Respond.  You could use that as a starting point for custom implementations.
https://github.com/madoublet/respond/blob/master/public/themes/bootstrap/plugins/slideshow.html

I have tried to make it really easy to create new plugins in Respond.  You can read the docs here: 
https://respondcms.com/documentation/creating-plugins

If you have suggestions for specific plugins, let me know.  I am hesitant to re-create the whole Bootstrap framework though.  I tend to just build plugins as I need them.
