### ISSUE TITLE
Missing "ace-builds" dependency in /package.json

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#483]
When I upgraded to RC2 and ran gulp, it gave me an error message about missing files in /node_modules/ace-builds .  I solved it by adding this line to package.json and running "npm update":

    "ace-builds": "1.2.5",

Is it OK if I commit that change to the RC3 branch?  I assume that is your working branch in preparation for the next RC release?

**Comment by madoublet** [comment]
Works for me.  Glad to hear from you as well.  :)

**Comment by WitteStier** [comment]
I have the same issue when following https://respondcms.com/documentation/installation-from-github.

@madoublet Nice project. I'm glad I found it.

**Comment by madoublet** [comment]
I pushed a fix for this and another bug to RC3.  My plan is to have a short RC3 (less than a week) and then possibly a short RC4 before the final release.

@WitteStier Thank you, glad you like the project.

**Comment by WitteStier** [comment]
RC3 branch works for me. Thanks.

**Comment by axis80** [comment]
Sorry I didn't get to this in time.  I was not near a computer for a few days.  Closing this issue as fixed.
