### ISSUE TITLE
empty file creates 500 error in app/Respond/Models/Page.php 

### ISSUE THREAD

**Issue by tstizzle** [madoublet/respond#485]
sometimes the wysiwyg editor accidentally creates a blank html file.  that file will, obviously, have no "role=main" statement.  when saving a component, page.php seems to be looping the html files in the site and looking for all "role=main" statements.

lacking this statement in a blank html file, app/Respond/Models/Page.php throws a 500 error at line 773: $els = $dom->find('[role=main]');  

page.php should insure $dom is valid before searching it.

**Comment by madoublet** [comment]
I pushed a fix for this in the RC4 branch.

**Comment by tstizzle** [comment]
thanks matthew!  LOVING your system.  thanks for all your hard work on it!

best,

-terence

**Comment by madoublet** [comment]
Closing...this is now fixed.
