### ISSUE TITLE
Themes folder location is hard coded and config parameter is not honored.

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#486]
In .env there is a parameter named THEMES_LOCATION, which is set by default to "public/themes/" .  Changing this parameter to point to a different folder does not work, as there are numerous locations throughout the app where the strings "themes/" and "public/themes/" are hard coded.

I can go through the app and fix these, except as I noted some of the hard-coded strings are folder locations (relative to the root of the respond installation) and some are URL locations (relative to the webroot, i.e. the "public" folder).  So, it is not possible for me to do that using the existing config parameter.

I see two options:

1. Change the config parameter so it's assumed to be relative to the public folder.  In other words, the default value would be "themes/" .  
2. Create a second config parameter called THEMES_URL, so there are different parameters for the folder on the filesystem and the URL location.

I vastly prefer the first solution, but don't want to implement that without your stamp of approval.  I am open to other solutions as well if you prefer that I go about it a different way.

Side note: should I assign the "rc5" label (or some other label) to issues that are release blockers?

**Comment by madoublet** [comment]
Sorry it took so long to reply to this.  I think #1 makes sense.  I am pretty sure the app already makes this assumption.

**Comment by axis80** [comment]
Pushed a fix to rc5.  Will leave this issue open in case you want to look over my work.

**Comment by madoublet** [comment]
This looks good. :)  Thank you.
