### ISSUE TITLE
Can email templates be translated?

### ISSUE THREAD

**Issue by joebordes** [madoublet/respond#490]
For example:

```
<h1>{{brand}}: {{ 'Reset Password' | translate}}</h1>

<p>
	{{ 'To reset your password, click on the' | translate}} <br>
	<a href="{{reset-url}}">{{reset-url}}</a>
</p>
```

or something similar

**Comment by madoublet** [comment]
I would recommend just editing the files in resources/email for now. What you describe could possibly work.  It might also be feasible to just have folders (e.g. resources/email/fr).

**Comment by joebordes** [comment]
ok. I will investigate further
