### ISSUE TITLE
Wrong link og:image

### ISSUE THREAD

**Issue by tobias533** [madoublet/respond#491]
When I try to post an article sur facebook, it doesn't show the picture. If I look into the HTML code, there is the relative path of the picture. In my opinion Facebook can not read the relative url, it need the whole path, (www.mysite.de/img/pic1.jpg). Thanks for a fix.

**Comment by madoublet** [comment]
This appears to be the case.  I think I can fix this issue with a site setting.

**Comment by madoublet** [comment]
This is fixed in RC6.  Documentation to be added soon.
