### ISSUE TITLE
Wrong link in navbar-brand

### ISSUE THREAD

**Issue by tobias533** [madoublet/respond#492]
I'm using Respond with "nonfriendly" links. All links work, exceptional on the logo (navbar-brand) in the menu:
<a class="navbar-brand" href="index"><img theme-logo src="resources/logo.png"></a>

**Comment by madoublet** [comment]
You will have to edit this manually for now.  I will update the themes to fix this issue going forward.

**Comment by madoublet** [comment]
This is fixed in RC6.
