### ISSUE TITLE
Single Site Mode

### ISSUE THREAD

**Issue by madoublet** [madoublet/respond#503]
For Respond installs that are built around a single site, create a way to bypass the create page and go directly to the login for that site.

**Comment by axis80** [comment]
How about a .env parameter indicating which page should be loaded when the
app starts, i.e. as the index page. That'd allow flexibility in a variety
of scenarios.

**Comment by madoublet** [comment]
Yeah, the env param makes sense.  I just need to figure out the Angular routing piece.  I think that is what is going to be tricky.

**Comment by madoublet** [comment]
I think I found a pretty straightforward way to accomplish this.  If I change the default route on the app from /create to /login, then I can specify a default site parameter that can be used if the site id is null.  The only real change is the default route.  

`DEFAULT_SITE=default`

**Comment by madoublet** [comment]
If a default_site is not specified, then perhaps I can show a dropdown of sites to choose from.

**Comment by axis80** [comment]
>
>
> If a default_site is not specified, then perhaps I can show a dropdown of
> sites to choose from.
>
I can imagine some circumstances when an admin wouldn't want to expose a
list of sites that are hosted on the server.

How about a text field where the user can enter the site shortname?  That's
how Shopify handles it.  See https://www.shopify.com/login .  Make sure to
click on the "Have Multiple Stores?" link below the green button.

>

**Comment by madoublet** [comment]
Yeah, I think you are right.  That would be much cleaner.

**Comment by madoublet** [comment]
The single login is now complete.  This should satisfy this request.
