### ISSUE TITLE
Question: zip in dist folder

### ISSUE THREAD

**Issue by twoSeats** [madoublet/respond#511]
It seems to me to be a bit much to have a 26mb zip as part of the source...
If I were to choose to pull from github as instructed on the download page of the respond site; I surely shouldn't be saddled with that huge zip as part of the deal...

The zip in the dist folder also doesn't have a version number, isn't this potentially confusing? shouldn't these zips be confined to the github releases page?

( speaking from the point of view of someone in a market where internet data is pricey and honestly every megabyte counts... )

**Comment by madoublet** [comment]
You make a really good point.  The reason why there is a zip file is that it contains the result of the TypeScript build not what is in the repo itself.  It is meant so you can just copy it and run it.  But, there is no need for it to be in the source repo.  Over the next few releases, I am working on separating the UI into its own repo.  I can also separate the zip releases into their own repo and that would also enable me to version them.

**Comment by madoublet** [comment]
That is unless there is a way to do this using Github releases.

**Comment by twoSeats** [comment]
I think the TypeScript build would be fine if relocated to Github releases. That's normally where I go to check for compiled things.
It would just need to be named appropriately I guess. In terms of what would be the best practice in this particular situation though; I don't really know... Someone with more experience maintaining a project here would likely have better advice.

**Comment by madoublet** [comment]
Thanks for the feedback here.  I am going to close this issue b/c it doesn't relate to a bug or issue in the project.
