### ISSUE TITLE
Thanks Cordially Brother. See my message

### ISSUE THREAD

**Issue by glerinsonum** [madoublet/respond#516]
@madoublet 

I would like to have and I your carrier regarding Web Developer for CMS and User Interface. 
I would like to have your videos, for learning about your skills, because i like to be a web developer for creating CMS for e-comerce,ads,news, etc etc, and user interface for page builder. 
So, send your videos to learning about cms developing.

**Comment by madoublet** [comment]
I am not sure what you are asking.  I am going to close this issue as it does not relate directly to am issue with the product.
