### ISSUE TITLE
Upgrading from Respond CMS 5.1

### ISSUE THREAD

**Issue by skorpeyon** [madoublet/respond#517]
Is there any way to upgrade from Respond CMS 5 to 6?  I'm not finding much in the way of documentation, but I would like to do so without losing data as I have several sites created in Respond.

**Comment by axis80** [comment]
There are instructions on migrating from Respond 5 to 6 at https://respondcms.com/documentation/migrating .  I have not tried them myself but it seems fairly straightforward.  Definitely make backups prior to attempting.

**Comment by madoublet** [comment]
There is no upgrade path, you can migrate sites as called out in the documentation above.  I am going to close this issue b/c it does not relate to a code specific issue with the product.
