### ISSUE TITLE
Unclear how to login after install

### ISSUE THREAD

**Issue by ssebs** [madoublet/respond#518]
I couldn't find any documentation on how to login to edit the site after it's created.

Maybe add this to the FAQ on the website?

**Comment by madoublet** [comment]
I will do that.  You login at https://app-to-respond.com/login/your-site.

**Comment by ssebs** [comment]
Got it thanks.

Also the themes install to app/public/themes, not resources/themes as per the documentation.

Thanks!

**Comment by madoublet** [comment]
Ah, thanks!  That is correct.  I will update that.
