### ISSUE TITLE
This project was abandoned?

### ISSUE THREAD

**Issue by ivent** [madoublet/respond#520]
Hello, I found this project something incredible to choose as a solution for my cms, but I found it strange to have spent 2 years without releasing a new release, this project was abandoned? Or are you planning to release an updated version?

**Comment by madoublet** [comment]
No, the project is still active.  I just stopped using the releases option and package the app using Gulp.  If you have any recommendations on doing this better, I am open to suggestions.

Thanks, Matt

**Comment by ivent** [comment]
Hello first of all congratulations for the work you did something incredible I am a densenvolvedor and I want to collaborate to help in the improvement of the project, thanks for the answer I will start working with him right now ...

**Comment by madoublet** [comment]
Thank you.
