### ISSUE TITLE
npm WARN The package typescript is included as both a dev and production dependency.

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#522]
Running npm install produces this warning:

`npm WARN The package typescript is included as both a dev and production dependency.`

I looked in package.json and saw that different versions of typescript are loaded in the dependencies and devDependencies sections.  The former loads version ^2.3.4 and the latter loads version 2.0.10.

It should be OK to remove the package from devDependencies, right?  My understanding is that all the packages in the main dependencies section always get installed, and the ones in the devDependencies section get installed as additional packages when the dev environment is specified.  I'm not positive that's how it works, though, so I figured I should ask before making any changes.

I realize it's just a warning, but I'm concerned that the development environment may be using a different version of typescript than the production one.  That could cause some serious hiccups, I would think.

**Comment by madoublet** [comment]
Yes, not sure why it is in both.  Probably just an oversight.  I will remove it from the devDependencies.

**Comment by madoublet** [comment]
FYI, this was fixed in the last release.  Just doing a little house cleaning.
