### ISSUE TITLE
list element

### ISSUE THREAD

**Issue by tobias533** [madoublet/respond#524]
There is an issue with the list element. The size of the pop up is to large,so , it is not possible to click the "Update" button. See attached file.
 
![list issue](https://user-images.githubusercontent.com/25417295/27260772-b508d29e-5434-11e7-8a09-bdc645523e2c.jpg)

**Comment by madoublet** [comment]
I will get this fixed.

**Comment by madoublet** [comment]
FYI, this was fixed in the last release.  Just doing a little house cleaning.
