### ISSUE TITLE
Opengraph url not correct

### ISSUE THREAD

**Issue by tobias533** [madoublet/respond#525]
For a page the og url is
`<meta property="og:url" content="http://www.mywebpage.de//" />`
so subdirectory and sitename is missing.
For better understanding, the og url should be a value like
`<meta property="og:url" content="http://www.mywebpage.de/page/site1.html" />`

**Comment by axis80** [comment]
The tags weren't showing up in your comment so I added backtick characters around them.

Unless Matt gets to it first, I should be able to fix this in the next week or so.

**Comment by madoublet** [comment]
Yeah, I will take a look at this soon.

**Comment by madoublet** [comment]
This is fixed now in the 6.1.2 branch.  It will move to production as part of the next release.
