### ISSUE TITLE
Connection to API failed 404 when MOD_REWRITE  enabled

### ISSUE THREAD

**Issue by anupmca** [madoublet/respond#528]
I am new to Respond and setting up local environment on my laptop. I have api running using MOD_REWRITE for other project on localhost. When I am hitting http://localhost/respond/app/public/install/
i get Connection to API failed and on clicking of api url, I get 404 error.

Also do I really need SSL for setting up sample demo website on my localhost?

**Comment by madoublet** [comment]
You can find information on how to get Lumen/Laravel to run locally here:
https://laravel.com/docs/4.2/quick#local-development-environment

Respond requires the application to run at the root of the URL (locally this would be http://localhost).

I am going to close this issue as it is not related to a deficiency in the project.

**Comment by madoublet** [comment]
I added instructions on how to install Respond locally.  Hopefully this will help you.
https://respondcms.com/documentation/installation-local
