### ISSUE TITLE
Not able to build Respond 6 from source code

### ISSUE THREAD

**Issue by nitinvarshney1983** [madoublet/respond#529]
Hi All,

I am completely new to Respond CMS. For learning purpose, I downloaded the source code of Respond 6 and tried to build it by running npm install and gulp command. 
But it is giving error to me. Can someone help? 

I am pasting the issues which I got by building the app.

~/Desktop/respond-master/respond-master
$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                                                   )
npm WARN @angular/core@4.3.1 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@4.3.1 requires a peer of zone.js@^0.8.4 but none was installed.
npm WARN @angular/http@4.3.1 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/router@4.3.1 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/upgrade@2.0.0 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN @angular/upgrade@2.0.0 requires a peer of @angular/compiler@^2.0.0 but none was installed.
npm WARN @angular/upgrade@2.0.0 requires a peer of @angular/platform-browser@^2.0.0 but none was installed.
npm WARN @angular/upgrade@2.0.0 requires a peer of @angular/platform-browser-dynamic@^2.0.0 but none was installed.
npm WARN angular2-in-memory-web-api@0.0.20 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angular2-in-memory-web-api@0.0.20 requires a peer of @angular/http@^2.0.0 but none was installed.
npm WARN ng2-translate@2.5.0 requires a peer of @angular/core@~2.0.0 but none was installed.
npm WARN ng2-translate@2.5.0 requires a peer of @angular/http@~2.0.0 but none was installed.

Also when I run gulp command, it gives error

$ gulp
[23:23:00] Using gulpfile ~\Desktop\respond-master\respond-master\gulpfile.js
TypeError: Cannot read property 'apply' of undefined
    at C:\Users\varshneyn\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:                                                   19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

I am using node version 6.10.0 and npm version 3.10.10

Please help.

**Comment by madoublet** [comment]
Respond offers a step-by-step guide for installing the software using Digital Ocean.  But, it should work for any Ubuntu-based VPS.  You can find the instructions here:
https://respondcms.com/documentation/install-on-digital-ocean

It might be possible to run it locally, but the challenge is getting Lumen (a subset of Laravel) to run locally.  You can find more information here:
https://laravel.com/docs/4.2/quick#local-development-environment

I am going to close this issue as it is not related to a deficiency in the project.

**Comment by madoublet** [comment]
I added instructions on how to install Respond locally.  Hopefully this will help you.
https://respondcms.com/documentation/installation-local
