### ISSUE TITLE
Docker build not working

### ISSUE THREAD

**Issue by Puresoft** [madoublet/respond#532]
Hi can not build from dockerfile since "coderstephen/php7:latest"
ist not valid any more.

thanks 
Robert

**Comment by madoublet** [comment]
I am honestly not too familiar with docker and do not maintain that piece of the project.  Perhaps, @ @coderstephen might be able to help out.

**Comment by madoublet** [comment]
I am not sure he is even on github anymore.

**Comment by fizzl** [comment]
I was messing with this also couple of weeks ago.
You can substitute coderstephens docker with

https://hub.docker.com/r/sagebind/php7-legacy/

However, I think there was other problem after that too. I ended up installing straight from git.

I'm not expert on docker either, so I hope someone else can fix the dockerfile, and perhaps provide builds on dockerhub.

**Comment by madoublet** [comment]
I honestly have not used Docker.  But, looking at the script, I feel like going the git installation route is more complicated than using the ZIP installation.  Here is a bash script I wrote to install Respond on Vagrant.  It is very lightweight.

https://github.com/madoublet/respond-box/blob/master/setup

Perhaps we can rework the docker script to behave more like the Vagrant script.

**Comment by Puresoft** [comment]
OK then I'll try to create a new docker file. I'll post issues here hope someone could help me then

**Comment by Puresoft** [comment]
Dockerfile is running but I get HTTP404 on respond login

GET http://192.168.100.50:8088/api/app/settings 404 (Not Found)

**Comment by Puresoft** [comment]
I get 404 for http://respond.puresoft.at:8088/api/sites/test 

If I do` a2enmod rewrite` I get 
Module rewrite already enabled

**Comment by madoublet** [comment]
@Puresoft The respond-box setup extracts Respond directly into **/var/www** folder because this is the default web root for Apache under Ubuntu.  So, this avoids having to change the document root or setting up virtual hosts for Respond.  This does (somewhat) lock the box into just being a Respond server.  That is why in the installation instructions I recommend using the **var/www/html/respond/app** folder.

If you extract your zip  to **/var/www/html/respond/app** then you would have to create an Apache .conf file to setup a VirtualHost for Respond.

I do feel that if you are going the Docker or Vagrant route, it is much more reasonable to install Respond directly into **/var/www**.

Let me know if this makes sense.

**Comment by Puresoft** [comment]
Makes sense, I'll try it that way.  I think I did it a few days ago and still got the 404 on the api url. Any way to debug that? 

I'll build a new image and post my issues

**Comment by madoublet** [comment]
@Puresoft I setup a test URL for the API at /api/sites/test.  You can see the demo example below.  This test just returns text.  Typically, if that is not working then a dependency is missing or you are pointing the URL at the wrong place.

https://demo.respondcms.com/api/sites/test

**Comment by Puresoft** [comment]
404 for api url again.

> On Ubuntu, by default, the Apache2 web server stores its documents in /var/www/html

I don't want to modify the apache config so I did  the same as in your current docker file,
using html as a link to /var/www/public

```docker
a2enmod rewrite
# restart apache

wget --content-disposition --no-check-certificate https://github.com/madoublet/respond/blob/master/dist/release.zip?raw=true

unzip -o release.zip -d /var/www

cd /var/www
rm -rf html
mkdir public/sites
mkdir resources/sites
chown -R www-data public/sites
chown -R www-data resources/sites
chown -R www-data storage

cp .env.example .env

# copied from the orig dockerfile since /var/www/html ist the DocumentRoot
ln -s /var/www/public html 
ln -s /var/www/node_modules public/node_modules
```

> I've to say that I'm running the container on a box without domain name and without the default port 80. So I'm accessing my site with this url `http://192.168.100.50:8088/install/`.

Hope you can help

**Comment by madoublet** [comment]
Give me a day or so.  I need to familiarize myself with Docker.  What you are doing seems like it should work, but I really need to see it first hand.

**Comment by Puresoft** [comment]
[Dockerfile.txt](https://github.com/madoublet/respond/files/1232293/Dockerfile.txt)

Attached my base docker file. (Ubuntu, apache, php). Build it run it and after that you 
can try your installation.

**Comment by Puresoft** [comment]
[Dockerfile.txt](https://github.com/madoublet/respond/files/1232376/Dockerfile.txt)

Attached the respond installation docker file. If you name the base-docker-file `ubuntu-web`
you can use this file to build/install respond

**Comment by madoublet** [comment]
FYI, I am still working on this.  I have it partially working.  This will be my focus over the next few days.  Hopefully, I can get it up and running.

**Comment by Puresoft** [comment]
Great, I'm very interested how your dockerfile looks like.

**Comment by madoublet** [comment]
I finally got this to work.  I still need to learn more about Docker in general before I push this to the repo.  But, this works for me.

Dockerfile
```
FROM nimmis/apache-php7
MAINTAINER Matthew Smith <matt@matthewsmith.com>

# install wget and unzip
RUN apt-get install -y \
    wget \
    unzip

# unzip Respond from latest dist
RUN  cd /var/www && \
wget --content-disposition --no-check-certificate https://github.com/madoublet/respond/blob/master/dist/release.zip?raw=true && \
unzip -o release.zip -d . && \
mkdir public/sites && \
mkdir resources/sites && \
chown -R www-data public/sites && \
chown -R www-data resources/sites && \
chown -R www-data storage  && \
cp .env.example .env

ADD ./vhost-config.conf /etc/apache2/sites-enabled/000-default.conf
RUN a2enmod rewrite

VOLUME /var/www

EXPOSE 80
VOLUME ["/var/www/public/sites", "/var/www/resources"]

# Default Command
CMD ["apache2ctl", "-D", "FOREGROUND"]
```

It requires an additional file (vhost-config.conf) to overwrite the default apache configuration file.  This is in the same directory as the Dockerfile.
```
<VirtualHost *:80>

	ServerAdmin matt@matthewsmith.com
	DocumentRoot /var/www/public

	<Directory /var/www>
    Options FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```

**Comment by Puresoft** [comment]
Mmmm don't like that it relies on `nimmis/apache-php7`
which is based on `nimmis/apache`  based on `nimmis/alpine-micro`  based on  `alpine:3.6`.

If "nimmis" stops maintaining his images then we are back in the same situation as now.

With alpine maybe the image-size (megabyte) is very small but the docker files to get this
thing working are complex.

In my opinion it should be as easy as php7, apache2 and respond.
With a pure linux image as a base, no external maintainer.

I'll try to get it working with my configuration, your `vhost-config.conf ` has some helpfull informations.

**Comment by madoublet** [comment]
@Puresoft That makes sense. It should be pretty easy now to get it to work with the base versions.  The most confusing piece was figuring out how to override the default apache configuration.

**Comment by Puresoft** [comment]
@madoublet Ahhh  thanks to your config it is working now on my side too.

I've now a respond Dockerfile with no dependencies. Great!
I'll post it here but want to fix some issues first.
1.) Apache restart not possible
2.) Docker kill/Stop leads to unstartable container
3.) ....

Could you help me on that,... what of this php modules do we really need?
```
	php-gd \
		php-curl \
		php-json \
		php-mbstring \
		php-mysql \
		php-opcache \
		php-xml \
		php-xsl \
		php-zip \
		php-soap \
```

**Comment by madoublet** [comment]
Definitely need: php-gd, php-curl, php-json, php-zip

I am not sure about the others.  I don't specifically use the other libraries, but a dependency might use them.

**Comment by Puresoft** [comment]
Thanks, I'm preparing a pull request now.

But found one issue while navigating around I see this in the console output:
`VM939 hashedit-min.js:1 GET http://192.168.100.50:8088/i18n/en.json?_=1504093899802 404 (Not Found)
(anonymous) @ VM939 hashedit-min.js:1`

Document root is: `/var/www/public`
There is no such folder. There is /assets/i18n/en.json but this does not look to be the right file.

**Comment by madoublet** [comment]
Ah, that does make sense.  I will get that fixed.

**Comment by madoublet** [comment]
Added this issue to track that bug: https://github.com/madoublet/respond/issues/539

**Comment by Puresoft** [comment]
Added a pull request: #540

**Comment by Puresoft** [comment]
@madoublet could you also update the docker files in the master branch?

**Comment by madoublet** [comment]
Do you think it makes sense to have a separate repo for the docker file?  I am somewhat new to Docker and not sure about the common patterns.  Having a separate repo would make it easier to merge PRs.  I currently have a separate repo for the Vagrant configuration: https://github.com/madoublet/respond-box

**Comment by Puresoft** [comment]
I'm also new to docker ;-), but sounds like a good idea.

**Comment by madoublet** [comment]
I was thinking we could have a respond-docker repo and then separate folders for configurations.  In the future, I am thinking it could look like the following:

respond-docker/apache/production
respond-docker/apache/development
respond-docker/nginx/production
respond-docker/nginx/development

For now, I will just keep it simple and include your docker file in the repo.

**Comment by madoublet** [comment]
I created the repo here:  https://github.com/madoublet/respond-docker

You can setup a PR there or I can add what you sent later today.

**Comment by madoublet** [comment]
I will remove the old docker folder in the next release.

**Comment by Puresoft** [comment]
Ok, could you move my pull-request to the new repo. Thanks.

**Comment by madoublet** [comment]
Ok, I created it here: https://github.com/madoublet/respond-docker

Let me know if I missed anything.
