### ISSUE TITLE
Attribute <img src=""> not working with relative path on ADMIN UI/Settings/Image or Logo or Background (theme depending)

### ISSUE THREAD

**Issue by AKAsebu** [madoublet/respond#545]
When you update favicon or image in the setting section of [Admin Respond UI](https://github.com/madoublet/respond-ui) the file is not charged because the src do not take the relative path `<img src="files/favicon.png"` but only the image name `<img src="favicon.png"`
![image](https://user-images.githubusercontent.com/9210668/30416849-fd23dffe-992d-11e7-971e-bedac33f33e3.png)

**Comment by madoublet** [comment]
Fixed in dev in madoublet/respond-ui.

**Comment by madoublet** [comment]
Fixed in latest release.
