### ISSUE TITLE
Byline plugin does not display informations only "account_box"

### ISSUE THREAD

**Issue by AKAsebu** [madoublet/respond#546]

**Comment by madoublet** [comment]
Which theme does this not work on?  I tested this on a few and it worked for me.

**Comment by AKAsebu** [comment]
Serene. But I can't reproduce 7 days later… It is definitly an error code `1D10t`. Sorry for that Matthew. 🙇

**Comment by madoublet** [comment]
No worries.  There is probably a bug in there somewhere.  Just keep an eye out and let me know if you see it again.

**Comment by AKAsebu** [comment]
The "last post" module does not display editor and date [http://blaisebernos.com/blog](http://blaisebernos.com/blog)
And in post page it the icon that is not displayed [http://blaisebernos.com/post/accastillage-ofcet-650](http://blaisebernos.com/post/accastillage-ofcet-650)

**Comment by madoublet** [comment]
Fixed in last release.
