### ISSUE TITLE
Can't Edit Menu Item "Is Nested?" once it is already passed to "Yes"

### ISSUE THREAD

**Issue by AKAsebu** [madoublet/respond#548]

**Comment by madoublet** [comment]
Fixed in dev.  This will be part of the next release.

**Comment by dsx0** [comment]
I tested it and found 2 other problems for this bug. :/

1) the function boolval:
A boolean TRUE value is converted to the string "1". Boolean FALSE is converted to "" (the empty string). This allows conversion back and forth between boolean and string values.
-> the if condition is not working correctly

2) if you dont change value of dropdown, an empty string will be sent
-> loose of Nested state if you only change title or something

i tried following:
removed:
#    $isNested = boolval($isNested);
#    if($isNested == 'false') {
#       $isNested = FALSE;
#    } else {
#       $isNested = TRUE;
#    }

and checked for empty string in if-condition below:
   if($menu != NULL) {

      // update the item at the index
      if($menu->items[$index] != NULL) {

        $menu->items[$index]['html'] = $html;
        $menu->items[$index]['cssClass'] = $cssClass;
        **if ($isNested != '') {
                $isNested = strtolower($isNested);
                $isNested = ($isNested == 'true' || $isNested == '1') ? true : false;
                $menu->items[$index]['isNested'] = $isNested;
        }**
        $menu->items[$index]['url'] = $url;
        $menu->items[$index]['target'] = $target;

      }

that worked for me.
maybe it helps.

best regards

**Comment by madoublet** [comment]
Thanks!  I will try that out.

**Comment by madoublet** [comment]
Fixed in last release.
