### ISSUE TITLE
Demo site don`t create

### ISSUE THREAD

**Issue by ravilrrr** [madoublet/respond#553]
Hi. Demo site don`t create
https://demo.respondcms.com/create

1 second in header a visible red line

**Comment by madoublet** [comment]
Thanks for the update!  Did you see a reCAPTCHA?  I think there might be a bug where the reCAPTCHA does not show up for some users.  I am digging into that.

**Comment by ravilrrr** [comment]
No. Can't see reCAPTCHA

**Comment by narigua** [comment]
@ravilrrr Clear your cache !
