### ISSUE TITLE
Reveal admin controls on hover instead of on click?

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#557]
Much of my workday involves knocking out quick edits for clients.  One of the things that made Respond 5 such a joy to work with, was that it made it very easy to do those.  I could just zip down the list of pages, find the one I want, and click on its large title.  Ditto for pretty much everything else in the admin interface - it was really easy to zip around at 100mph making adjustments.

Respond 6 involves a lot of clicking.  It takes at least twice as long to get anything done because you have to click once to reveal the controls, then move your mouse to find the control you want to click on.

I've created a working mockup to illustrate a different behavior that I think will make for easier day-to-day use.  The mockup is at http://www.axis80.com/ext/respond/admin.html .  This is not a responsive mockup - you must view it on a desktop computer.

Here are the key differences:

- Instead of clicking on a page to reveal its controls, you hover over it
- The page you're currently hovering over takes on a grey background to provide feedback.  that makes it easier to slam the pointer around quickly to locate the page you want to edit
- Controls use a fade-in animation.  That means when you are moving the pointer quickly past them they won't appear and clutter up the display.  It is only when you start to slow the pointer down that they appear.
- User can click on the page title to edit the page (this will work with objects other than pages, as well). 
- Page title is slightly larger to make it easier to hit with the pointer when moving at high speeds.
- Control and page title links change color on hover to provide feedback 

I considered taking it farther than this and making it so that clicking anywhere in the grey background of the hover area would edit the page (i.e. perform the default action).  I thought that might be pushing it, though.

Look forward to hearing feedback from others on whether this proposed change makes sense at all.

**Comment by AKAsebu** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/058e674c-7fb0-4e3c-9856-9f5b00e66682-8ad0e947-6a36-48e7-b01f-b25d2240827c-v1.png?transparent=1&palette=1&width=246)

**Comment by madoublet** [comment]
This looks good.  I will start implementing this.

**Comment by madoublet** [comment]
This is complete.
