### ISSUE TITLE
Can't delete last form submission

### ISSUE THREAD

**Issue by patrikhuber** [madoublet/respond#569]
Hi, I'm having another issue :'( Again I'd guess this is an issue with respond, and not something with my setup (which is all the default, no modifications).

Sometimes (not always weirdly...), the last entry in "Submissions" can't be deleted. So I submit 3-4 items, then delete them, and sometimes the last one can't be deleted. If I then add more submissions again and delete them in a different order, I can delete all of them.

I can also check `submissions.json` and the last entry stays, e.g. this one:

```
{
    "4": {
        "id": "{2B8107E3-2569-218F-3FBE-3E26F1434512}",
        "name": "h",
        "url": "https:\/\/respond.mysite.com\/sites\/mysite\/page\/contact.html?formid=contact-us&formstatus=success",
        "formId": "contact-us",
        "date": "Mon Jan 01 2018 21:34:43 +0000",
        "fields": [
            {
                "id": "name",
                "value": "h"
            },
            {
                "id": "email",
                "value": "h"
            },
            {
                "id": "phone",
                "value": ""
            },
            {
                "id": "preferred",
                "value": " Phone"
            },
            {
                "id": "comments",
                "value": ""
            },
            {
                "id": "g-recaptcha-response",
                "value": "abc"
            }
        ]
    }
}
```

**Comment by madoublet** [comment]
I am aware of this one.  See https://github.com/madoublet/respond/issues/562.  I am going to close this one for now.

**Comment by madoublet** [comment]
FYI, just closing this b/c it is a duplicate.  It is on my list of things to work for the January release.

**Comment by patrikhuber** [comment]
Oh good! Sorry for the duplicate! I searched the issues each time before posting a new one, but for this one I didn't... ;-)
