### ISSUE TITLE
Gulp fails during installation of 6.7.0 due to missing file

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#580]
I just upgraded to 6.7.0 (via git) and got this error when I ran gulp:

    [00:57:16] Using gulpfile /path/to/respond/gulpfile.js
    [00:57:16] Starting 'default'...
    [00:57:16] Starting 'copy-folders'...
    [00:57:16] Finished 'copy-folders' after 54 ms
    [00:57:16] Starting 'copy-js'...
    [00:57:16] 'copy-js' errored after 16 ms
    [00:57:16] Error: File not found with singular glob: 
    /path/to/respond/node_modules/moment/min/moment-with-locales.min.js (if this was purposeful, use `allowEmpty` option)

Apparently what's happened is that the file path of the .js file has changed since you split the UI off as a separate node module.  Changing the path in the gulpfile to `node_modules/respond-ui/node_modules/moment/min/moment-with-locales.min.js` will fix it, however I'm not sure whether it is better to fix it that way, or to instead list the moment package as a dependency for the main respond package.  I'm guessing it's better to change the path in gulpfile but I thought I should ask first.

**Comment by madoublet** [comment]
I will get this fixed this weekend.  I believe it can just be removed from the gulpfile.js as these references have been moved to respond-ui.

**Comment by madoublet** [comment]
This should be fixed now.

**Comment by axis80** [comment]
I just did `git pull`, then `rm -rf node_modules`, then `npm install`, then `gulp`.  Everything completed cleanly and I was able to log into the CMS so I would say this specific error message is fixed now.  

Unfortunately I have not been able to get the page editor to load, and that still seems to be the case even after executing the above commands.  I will open a separate issue about that.

**Comment by axis80** [comment]
Please disregard my mention above about not being able to load the editor.  In documenting that issue I discovered it only happens on my custom theme, not on any of the themes that are included with Respond.  I am closing this issue now as I believe it is 100% solved.
