### ISSUE TITLE
Installation problem on Laragon

### ISSUE THREAD

**Issue by peterb776** [madoublet/respond#587]
I'm trying to install Respond on Laragon Full 3.1.9 on my Windows 10 PC and get the following error messages from the installation tests:

Warning: require(../../vendor/autoload.php): failed to open stream: No such file or directory in C:\laragon\www\respondcms\public\install\index.php on line 111

Fatal error: require(): Failed opening required '../../vendor/autoload.php' (include_path='.;C:/laragon/etc/php/pear') in C:\laragon\www\respondcms\public\install\index.php on line 111

What is the 'vendor/autoload.php' that's missing?

Thanks,
Peter

**Comment by madoublet** [comment]
I am not familiar with Laragon.  However, it looks like a useful tool.  The autoload.php file is used by Composer (see https://getcomposer.org/).  Composer loads the dependency files into the vendor directory and the autoload.php references those files. The Respond repo does not include the vendor files.  However, the distribution zip file (dist/release.zip) does include the vendor files.

**Comment by peterb776** [comment]
OK, it's probably the lack of Composer. But this all makes the installation a tedious slog, so I might just give up as I'm not sure that I will be able to sort out this issue on my hosting Company's server!

I've installed lots of different CMSs without any problems, so it's a pity that Respond is so much more difficult as it looks very useful.
