### ISSUE TITLE
Hyperlinking a span of text causes that text to disappear

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#590]
When one selects a portion of text within a text element and then applies a hyperlink to it, that span of text disappears.

### Steps to reproduce

1. Drag a paragraph onto the page.
2. Change the default "tap to update" text to "now is the time for all good monkeys to get funky".
3. Click elsewhere within the page content to ensure your change is recorded in the DOM (see #589 ).
4. Select the word "monkeys".
5. Click the link button in the left column.
6. In the "link" field, select a page.
7. Click update.
8. The highlighted text disappears entirely.  Viewing the HTML of the element shows that the opening/closing `a` tags are added, but the text between them is blank.

**Comment by madoublet** [comment]
Ditto.  I will look at this while addressing the other issue.

**Comment by madoublet** [comment]
Got this fixed in my dev build.  It should release soon.

**Comment by axis80** [comment]
I can confirm this is now fixed, so I am closing this issue as well.
