### ISSUE TITLE
Publishing a component results in HTTP 400 (Bad Request) error

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#591]
Steps to reproduce:

1. Create a component
2. Click Edit to edit the component
3. Change the headline text to "New Component2" (or any other text)
4. Click the "Publish" button

Result:

- The browser console displays **VM256:1 POST http://www.example.com/api/pages/publish 400 (Bad Request)** and the component is not saved

I've spent some time trying to debug this but haven't yet had any luck.  The only thing worth noting is that I am seeing a lot of inconsistency with the key/value items in Chrome's local storage.  For example, the respond-ui source code shows that the items `respond.pageUrl` and `respond.editMode` are set when a component is edited, however I am not seeing those show up in local storage.

It's possible this is a misconfiguration of some sort on my end, however I do note that publishing pages works just fine.

**Comment by madoublet** [comment]
I put in a fix for this error.  Some code was not properly ordered.  I am not sure why this just materialized though as I do use components a lot.  It might have been that I was just using the "code only" components.  Regardless, it should be fixed after update.

**Comment by madoublet** [comment]
Derrick, as an aside, I am not sure you are aware but I created some helpful scripts to quickly manage Respond.  The update_respond script is especially useful to quickly update your build.

See: https://github.com/madoublet/respond-scripts

**Comment by axis80** [comment]
Thanks, Matt.  I was not aware of those scripts.  I wrote something similar using Deployer (https://deployer.org/) that allows me to deploy any Git branch to my production site.
I will take the latest fixes for a spin today and let you know how it goes.

**Comment by axis80** [comment]
I can confirm this is now fixed, so I am closing this issue.
