### ISSUE TITLE
npm install fails with error: pathspec '4.0' did not match any file

### ISSUE THREAD

**Issue by Wikkjaz** [madoublet/respond#598]
On new installation `npm install` fails with 
``npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout 4.0
npm ERR! error: pathspec '4.0' did not match any file(s) known to git.``

As I understand, gulp remove their #4.0 branch and need dependencies to new one.

Details about gulp getting from here
https://stackoverflow.com/a/52942546

**Comment by cweiske** [comment]
Solution:

```
-    "gulp": "github:gulpjs/gulp#4.0",
+    "gulp": "^4.0",
```

**Comment by axis80** [comment]
Fixed in the master branch. Thanks to @Wikkjaz and @cweiske for the issue report and the fix.
