### ISSUE TITLE
Clarify "commercial license"

### ISSUE THREAD

**Issue by cweiske** [madoublet/respond#601]
The LICENSE file says 

> Licensed for personal and/or commercial with a valid license purchased from respondcms.com.

But there is no purchase button on the website (anymore?).
What's the current license now?

The website says it's open source, but this this not a valid OSL license.

**Comment by madoublet** [comment]
Sorry about that.  It is free to use.  I will update the license.

**Comment by madoublet** [comment]
License updated to MIT.
