### ISSUE TITLE
2.9: "Uncaught Error: Dropzone already attached." when loading page in admin

### ISSUE THREAD

**Issue by axis80** [madoublet/respond#96]
This may be related to issue #97 .

Steps to reproduce:
1.  Open Google Chrome and press Ctrl-Shift-J to open the Javascript console.
2.  Load an existing page from the admin.
3.  You'll see this error message in the console:

Uncaught Error: Dropzone already attached. dropzone.js?v=2.9.1:642
Dropzone dropzone.js?v=2.9.1:642
Dropzone.discover dropzone.js?v=2.9.1:1503
Dropzone._autoDiscoverFunction dropzone.js?v=2.9.1:1741
init

Here are a few links that may be relevant:

https://github.com/enyo/dropzone/issues/492
https://github.com/enyo/dropzone/issues/65
https://github.com/CenterForOpenScience/hgrid/issues/5

**Comment by FaiqueAli** [comment]
I am also facing the same issue although I remove from programatically from js and also tried to put
Dropzone.autoDiscover = false; and  Dropzone..options.myAwesomeDropzone = false;

I hope I added references or files more thane one time.
any help is appreciated!
Thanks-
S.Faiq
